// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: albums.sql

package store

import (
	"context"
	"database/sql"
)

const countAlbums = `-- name: CountAlbums :many
SELECT available, count(*) AS total FROM albums GROUP BY available ORDER BY available
`

type CountAlbumsRow struct {
	Available int64
	Total     int64
}

// CountAlbums counts the albums that are available (1) and those that are
// not (0), for the state of the library (DESIGN.md 6.5).
func (q *Queries) CountAlbums(ctx context.Context) ([]CountAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, countAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountAlbumsRow
	for rows.Next() {
		var i CountAlbumsRow
		if err := rows.Scan(&i.Available, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumCover = `-- name: GetAlbumCover :one
SELECT rel_path, cover_rel, cover_sha256, cover_mime, cover_size, cover_mtime_ns, available
FROM albums
WHERE id = ?
`

type GetAlbumCoverRow struct {
	RelPath      string
	CoverRel     sql.NullString
	CoverSha256  sql.NullString
	CoverMime    sql.NullString
	CoverSize    sql.NullInt64
	CoverMtimeNs sql.NullInt64
	Available    int64
}

// GetAlbumCover returns what serving the cover of an album needs (DESIGN.md
// 9.2): the folder of the album and the cover the scanner saw in it, with
// the size and the time of its file. The cover columns are null for an
// album without a cover. An album that was never indexed is sql.ErrNoRows.
func (q *Queries) GetAlbumCover(ctx context.Context, id string) (GetAlbumCoverRow, error) {
	row := q.db.QueryRowContext(ctx, getAlbumCover, id)
	var i GetAlbumCoverRow
	err := row.Scan(
		&i.RelPath,
		&i.CoverRel,
		&i.CoverSha256,
		&i.CoverMime,
		&i.CoverSize,
		&i.CoverMtimeNs,
		&i.Available,
	)
	return i, err
}

const getAlbumCoverByHash = `-- name: GetAlbumCoverByHash :one
SELECT rel_path, cover_rel, cover_sha256, cover_mime, cover_size, cover_mtime_ns, available
FROM albums
WHERE cover_sha256 = ? AND available = 1
ORDER BY seq
LIMIT 1
`

type GetAlbumCoverByHashRow struct {
	RelPath      string
	CoverRel     sql.NullString
	CoverSha256  sql.NullString
	CoverMime    sql.NullString
	CoverSize    sql.NullInt64
	CoverMtimeNs sql.NullInt64
	Available    int64
}

// GetAlbumCoverByHash returns an available album that has the cover with
// that SHA-256, the oldest one if several do: where the thumbnails of the
// cover are made from, ahead of any request (DESIGN.md 9.2). No such album
// is sql.ErrNoRows.
func (q *Queries) GetAlbumCoverByHash(ctx context.Context, coverSha256 sql.NullString) (GetAlbumCoverByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAlbumCoverByHash, coverSha256)
	var i GetAlbumCoverByHashRow
	err := row.Scan(
		&i.RelPath,
		&i.CoverRel,
		&i.CoverSha256,
		&i.CoverMime,
		&i.CoverSize,
		&i.CoverMtimeNs,
		&i.Available,
	)
	return i, err
}

const getIndexedAlbum = `-- name: GetIndexedAlbum :one
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.id = ?
`

type GetIndexedAlbumRow struct {
	Album      Album
	ArtistName string
}

// GetIndexedAlbum returns the row of an album, available or not, with the
// name of its artist: what the indexer starts from (DESIGN.md 6.3 step 3).
// An album that was never indexed is sql.ErrNoRows.
func (q *Queries) GetIndexedAlbum(ctx context.Context, id string) (GetIndexedAlbumRow, error) {
	row := q.db.QueryRowContext(ctx, getIndexedAlbum, id)
	var i GetIndexedAlbumRow
	err := row.Scan(
		&i.Album.Seq,
		&i.Album.ID,
		&i.Album.ArtistID,
		&i.Album.ArtistKey,
		&i.Album.Title,
		&i.Album.TitleKey,
		&i.Album.Year,
		&i.Album.YearKey,
		&i.Album.Genre,
		&i.Album.Compilation,
		&i.Album.RelPath,
		&i.Album.AlbumRevision,
		&i.Album.RenderVersion,
		&i.Album.ReceiptHash,
		&i.Album.CoverRel,
		&i.Album.CoverSha256,
		&i.Album.CoverMime,
		&i.Album.CoverSize,
		&i.Album.CoverMtimeNs,
		&i.Album.TrackCount,
		&i.Album.DurationMs,
		&i.Album.Available,
		&i.Album.FirstSeenAt,
		&i.Album.UpdatedAt,
		&i.ArtistName,
	)
	return i, err
}

const listAlbumIDsByArtist = `-- name: ListAlbumIDsByArtist :many
SELECT id FROM albums WHERE artist_id = ? AND available = 1 ORDER BY seq
`

// ListAlbumIDsByArtist returns the ids of the available albums of an artist.
func (q *Queries) ListAlbumIDsByArtist(ctx context.Context, artistID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumIDsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumStates = `-- name: ListAlbumStates :many
SELECT id, artist_id, rel_path, receipt_hash, available FROM albums ORDER BY seq
`

type ListAlbumStatesRow struct {
	ID          string
	ArtistID    string
	RelPath     string
	ReceiptHash string
	Available   int64
}

// ListAlbumStates returns, for every album of the index, available or not,
// what a scan compares with the library (DESIGN.md 6.1, P3): the folder and
// the receipt it was indexed from. The rows are in the order they were
// created.
func (q *Queries) ListAlbumStates(ctx context.Context) ([]ListAlbumStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumStatesRow
	for rows.Next() {
		var i ListAlbumStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.ArtistID,
			&i.RelPath,
			&i.ReceiptHash,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumTitles = `-- name: ListAlbumTitles :many
SELECT id, title FROM albums ORDER BY seq
`

type ListAlbumTitlesRow struct {
	ID    string
	Title string
}

// ListAlbumTitles returns the title of every album: what its title_key is
// computed from (DESIGN.md 5.5).
func (q *Queries) ListAlbumTitles(ctx context.Context) ([]ListAlbumTitlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumTitles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumTitlesRow
	for rows.Next() {
		var i ListAlbumTitlesRow
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAlbumTitleKey = `-- name: SetAlbumTitleKey :exec
UPDATE albums SET title_key = ? WHERE id = ?
`

type SetAlbumTitleKeyParams struct {
	TitleKey []byte
	ID       string
}

// SetAlbumTitleKey gives an album the sort key of its title, computed again
// after the collation changed (DESIGN.md 5.5, T26).
func (q *Queries) SetAlbumTitleKey(ctx context.Context, arg SetAlbumTitleKeyParams) error {
	_, err := q.db.ExecContext(ctx, setAlbumTitleKey, arg.TitleKey, arg.ID)
	return err
}

const setAlbumUnavailable = `-- name: SetAlbumUnavailable :exec
UPDATE albums SET available = 0, updated_at = ? WHERE id = ? AND available = 1
`

type SetAlbumUnavailableParams struct {
	UpdatedAt int64
	ID        string
}

// SetAlbumUnavailable records that the folder of an album is gone (DESIGN.md
// 6.4). The row stays, with what was last known of the album (I3), and comes
// back with the same id if its folder does.
func (q *Queries) SetAlbumUnavailable(ctx context.Context, arg SetAlbumUnavailableParams) error {
	_, err := q.db.ExecContext(ctx, setAlbumUnavailable, arg.UpdatedAt, arg.ID)
	return err
}

const setArtistKeyOfAlbums = `-- name: SetArtistKeyOfAlbums :exec
UPDATE albums SET artist_key = ? WHERE artist_id = ?
`

type SetArtistKeyOfAlbumsParams struct {
	ArtistKey []byte
	ArtistID  string
}

// SetArtistKeyOfAlbums gives every album of an artist the sort key of the
// artist, of which albums.artist_key is a copy (DESIGN.md 5.2), after the
// name of the artist changed.
func (q *Queries) SetArtistKeyOfAlbums(ctx context.Context, arg SetArtistKeyOfAlbumsParams) error {
	_, err := q.db.ExecContext(ctx, setArtistKeyOfAlbums, arg.ArtistKey, arg.ArtistID)
	return err
}

const updateAlbumCounters = `-- name: UpdateAlbumCounters :exec
UPDATE albums SET
    track_count = (
        SELECT count(*) FROM tracks
        WHERE tracks.album_id = albums.id AND tracks.available = 1),
    duration_ms = (
        SELECT coalesce(sum(tracks.duration_ms), 0) FROM tracks
        WHERE tracks.album_id = albums.id AND tracks.available = 1)
WHERE albums.id = ?
`

// UpdateAlbumCounters counts the available tracks of an album again, and
// adds up their known durations (DESIGN.md 5.2).
func (q *Queries) UpdateAlbumCounters(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateAlbumCounters, id)
	return err
}

const upsertAlbum = `-- name: UpsertAlbum :exec
INSERT INTO albums (
    id, artist_id, artist_key, title, title_key, year, year_key, genre, compilation,
    rel_path, album_revision, render_version, receipt_hash,
    cover_rel, cover_sha256, cover_mime, cover_size, cover_mtime_ns,
    track_count, duration_ms, available, first_seen_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    0, 0, 1, ?, ?
)
ON CONFLICT (id) DO UPDATE SET
    artist_id = excluded.artist_id,
    artist_key = excluded.artist_key,
    title = excluded.title,
    title_key = excluded.title_key,
    year = excluded.year,
    year_key = excluded.year_key,
    genre = excluded.genre,
    compilation = excluded.compilation,
    rel_path = excluded.rel_path,
    album_revision = excluded.album_revision,
    render_version = excluded.render_version,
    receipt_hash = excluded.receipt_hash,
    cover_rel = excluded.cover_rel,
    cover_sha256 = excluded.cover_sha256,
    cover_mime = excluded.cover_mime,
    cover_size = excluded.cover_size,
    cover_mtime_ns = excluded.cover_mtime_ns,
    available = 1,
    updated_at = excluded.updated_at
`

type UpsertAlbumParams struct {
	ID            string
	ArtistID      string
	ArtistKey     []byte
	Title         string
	TitleKey      []byte
	Year          sql.NullInt64
	YearKey       int64
	Genre         sql.NullString
	Compilation   int64
	RelPath       string
	AlbumRevision int64
	RenderVersion string
	ReceiptHash   string
	CoverRel      sql.NullString
	CoverSha256   sql.NullString
	CoverMime     sql.NullString
	CoverSize     sql.NullInt64
	CoverMtimeNs  sql.NullInt64
	FirstSeenAt   int64
	UpdatedAt     int64
}

// UpsertAlbum writes what the indexer knows of an album and makes it
// available (DESIGN.md 6.3 step 8). A new album has no tracks yet; a known
// one keeps its first_seen_at and its counters, which UpdateAlbumCounters
// sets once the tracks are written. The row is never deleted (I3).
func (q *Queries) UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlbum,
		arg.ID,
		arg.ArtistID,
		arg.ArtistKey,
		arg.Title,
		arg.TitleKey,
		arg.Year,
		arg.YearKey,
		arg.Genre,
		arg.Compilation,
		arg.RelPath,
		arg.AlbumRevision,
		arg.RenderVersion,
		arg.ReceiptHash,
		arg.CoverRel,
		arg.CoverSha256,
		arg.CoverMime,
		arg.CoverSize,
		arg.CoverMtimeNs,
		arg.FirstSeenAt,
		arg.UpdatedAt,
	)
	return err
}
