// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artists.sql

package store

import (
	"context"
)

const getArtist = `-- name: GetArtist :one
SELECT seq, id, name, sort_key FROM artists WHERE id = ?
`

// GetArtist returns an artist by its id, which is the UUIDv5 of the identity
// key of its name (DESIGN.md 5.4). An unknown id is sql.ErrNoRows.
func (q *Queries) GetArtist(ctx context.Context, id string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtist, id)
	var i Artist
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.Name,
		&i.SortKey,
	)
	return i, err
}

const listArtists = `-- name: ListArtists :many
SELECT seq, id, name, sort_key FROM artists ORDER BY seq
`

// ListArtists returns every artist, in the order the rows were created: the
// names their sort keys are computed from (DESIGN.md 5.5).
func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.Name,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setArtistSortKey = `-- name: SetArtistSortKey :exec
UPDATE artists SET sort_key = ? WHERE id = ?
`

type SetArtistSortKeyParams struct {
	SortKey []byte
	ID      string
}

// SetArtistSortKey gives an artist the sort key of its name, computed again
// after the collation changed (DESIGN.md 5.5, T26).
func (q *Queries) SetArtistSortKey(ctx context.Context, arg SetArtistSortKeyParams) error {
	_, err := q.db.ExecContext(ctx, setArtistSortKey, arg.SortKey, arg.ID)
	return err
}

const upsertArtist = `-- name: UpsertArtist :exec
INSERT INTO artists (id, name, sort_key) VALUES (?, ?, ?)
ON CONFLICT (id) DO UPDATE SET name = excluded.name, sort_key = excluded.sort_key
`

type UpsertArtistParams struct {
	ID      string
	Name    string
	SortKey []byte
}

// UpsertArtist creates an artist, or gives a known one the name and the sort
// key of the last album that was indexed for it: two names with one identity
// key (another case, other white space) are one artist. The row is never
// deleted (I3).
func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtist, arg.ID, arg.Name, arg.SortKey)
	return err
}
