// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"
	"database/sql"
)

const getAvailableAlbum = `-- name: GetAvailableAlbum :one
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.id = ?1 AND albums.available = 1
`

type GetAvailableAlbumRow struct {
	Album      Album
	ArtistName string
}

// GetAvailableAlbum returns an album with the name of its artist, if it is
// available. An album that is not, or was never indexed, is sql.ErrNoRows.
func (q *Queries) GetAvailableAlbum(ctx context.Context, id string) (GetAvailableAlbumRow, error) {
	row := q.db.QueryRowContext(ctx, getAvailableAlbum, id)
	var i GetAvailableAlbumRow
	err := row.Scan(
		&i.Album.Seq,
		&i.Album.ID,
		&i.Album.ArtistID,
		&i.Album.ArtistKey,
		&i.Album.Title,
		&i.Album.TitleKey,
		&i.Album.Year,
		&i.Album.YearKey,
		&i.Album.Genre,
		&i.Album.Compilation,
		&i.Album.RelPath,
		&i.Album.AlbumRevision,
		&i.Album.RenderVersion,
		&i.Album.ReceiptHash,
		&i.Album.CoverRel,
		&i.Album.CoverSha256,
		&i.Album.CoverMime,
		&i.Album.CoverSize,
		&i.Album.CoverMtimeNs,
		&i.Album.TrackCount,
		&i.Album.DurationMs,
		&i.Album.Available,
		&i.Album.FirstSeenAt,
		&i.Album.UpdatedAt,
		&i.ArtistName,
	)
	return i, err
}

const getTrackFile = `-- name: GetTrackFile :one
SELECT tracks.available, albums.rel_path AS album_rel_path, tracks.rel_path,
    tracks.file_size, tracks.file_mtime_ns, tracks.file_sha256, tracks.codec,
    tracks.lyrics_rel, tracks.lyrics_sha256
FROM tracks
JOIN albums ON albums.id = tracks.album_id
WHERE tracks.id = ?
`

type GetTrackFileRow struct {
	Available    int64
	AlbumRelPath string
	RelPath      string
	FileSize     int64
	FileMtimeNs  int64
	FileSha256   string
	Codec        string
	LyricsRel    sql.NullString
	LyricsSha256 sql.NullString
}

// GetTrackFile returns what the index says of the files of a track,
// available or not: the folder of its album and its own path, both
// relative to library/ and written only by the scanner (I2), the size, the
// time and the SHA-256 the scanner saw, its codec, and its lyrics file
// (DESIGN.md 9.1, 9.3).
func (q *Queries) GetTrackFile(ctx context.Context, id string) (GetTrackFileRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackFile, id)
	var i GetTrackFileRow
	err := row.Scan(
		&i.Available,
		&i.AlbumRelPath,
		&i.RelPath,
		&i.FileSize,
		&i.FileMtimeNs,
		&i.FileSha256,
		&i.Codec,
		&i.LyricsRel,
		&i.LyricsSha256,
	)
	return i, err
}

const getTrackWithAlbum = `-- name: GetTrackWithAlbum :one
SELECT tracks.seq, tracks.id, tracks.album_id, tracks.fingerprint, tracks.fp_version, tracks.occurrence, tracks.disc, tracks."no", tracks.title, tracks.artist, tracks.genre, tracks.rel_path, tracks.file_size, tracks.file_mtime_ns, tracks.file_sha256, tracks.codec, tracks.sample_rate, tracks.channels, tracks.bit_depth, tracks.bitrate, tracks.duration_ms, tracks.lyrics_rel, tracks.lyrics_sha256, tracks.rg_track_gain, tracks.rg_track_peak, tracks.rg_album_gain, tracks.rg_album_peak, tracks.available, tracks.updated_at,
    albums.title AS album_title, albums.year AS album_year, albums.cover_sha256 AS album_cover_sha256,
    albums.artist_id AS album_artist_id, artists.name AS album_artist_name,
    EXISTS (SELECT 1 FROM favorites
            WHERE favorites.user_id = ?1 AND favorites.track_id = tracks.id) AS favorite
FROM tracks
JOIN albums ON albums.id = tracks.album_id
JOIN artists ON artists.id = albums.artist_id
WHERE tracks.id = ?2
`

type GetTrackWithAlbumParams struct {
	UserID string
	ID     string
}

type GetTrackWithAlbumRow struct {
	Track            Track
	AlbumTitle       string
	AlbumYear        sql.NullInt64
	AlbumCoverSha256 sql.NullString
	AlbumArtistID    string
	AlbumArtistName  string
	Favorite         bool
}

// GetTrackWithAlbum returns a track, available or not, with what the API
// shows of its album, which is always there (the rows are never deleted,
// I3), and whether it is a favorite of the user. No such track is
// sql.ErrNoRows.
func (q *Queries) GetTrackWithAlbum(ctx context.Context, arg GetTrackWithAlbumParams) (GetTrackWithAlbumRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackWithAlbum, arg.UserID, arg.ID)
	var i GetTrackWithAlbumRow
	err := row.Scan(
		&i.Track.Seq,
		&i.Track.ID,
		&i.Track.AlbumID,
		&i.Track.Fingerprint,
		&i.Track.FpVersion,
		&i.Track.Occurrence,
		&i.Track.Disc,
		&i.Track.No,
		&i.Track.Title,
		&i.Track.Artist,
		&i.Track.Genre,
		&i.Track.RelPath,
		&i.Track.FileSize,
		&i.Track.FileMtimeNs,
		&i.Track.FileSha256,
		&i.Track.Codec,
		&i.Track.SampleRate,
		&i.Track.Channels,
		&i.Track.BitDepth,
		&i.Track.Bitrate,
		&i.Track.DurationMs,
		&i.Track.LyricsRel,
		&i.Track.LyricsSha256,
		&i.Track.RgTrackGain,
		&i.Track.RgTrackPeak,
		&i.Track.RgAlbumGain,
		&i.Track.RgAlbumPeak,
		&i.Track.Available,
		&i.Track.UpdatedAt,
		&i.AlbumTitle,
		&i.AlbumYear,
		&i.AlbumCoverSha256,
		&i.AlbumArtistID,
		&i.AlbumArtistName,
		&i.Favorite,
	)
	return i, err
}

const listAlbumsByAddedAsc = `-- name: ListAlbumsByAddedAsc :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
ORDER BY albums.first_seen_at, albums.id
LIMIT ?2
`

type ListAlbumsByAddedAscParams struct {
	ArtistID sql.NullString
	PageSize int64
}

type ListAlbumsByAddedAscRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByAddedAsc returns the first page of the available albums by
// (first_seen_at, id), ascending.
func (q *Queries) ListAlbumsByAddedAsc(ctx context.Context, arg ListAlbumsByAddedAscParams) ([]ListAlbumsByAddedAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByAddedAsc, arg.ArtistID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByAddedAscRow
	for rows.Next() {
		var i ListAlbumsByAddedAscRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByAddedAscAfter = `-- name: ListAlbumsByAddedAscAfter :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
  AND (albums.first_seen_at, albums.id) > (CAST(?2 AS INTEGER), CAST(?3 AS TEXT))
ORDER BY albums.first_seen_at, albums.id
LIMIT ?4
`

type ListAlbumsByAddedAscAfterParams struct {
	ArtistID    sql.NullString
	FirstSeenAt int64
	AfterID     string
	PageSize    int64
}

type ListAlbumsByAddedAscAfterRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByAddedAscAfter returns the page of ListAlbumsByAddedAsc
// after the album with that key.
func (q *Queries) ListAlbumsByAddedAscAfter(ctx context.Context, arg ListAlbumsByAddedAscAfterParams) ([]ListAlbumsByAddedAscAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByAddedAscAfter,
		arg.ArtistID,
		arg.FirstSeenAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByAddedAscAfterRow
	for rows.Next() {
		var i ListAlbumsByAddedAscAfterRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByAddedDesc = `-- name: ListAlbumsByAddedDesc :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
ORDER BY albums.first_seen_at DESC, albums.id DESC
LIMIT ?2
`

type ListAlbumsByAddedDescParams struct {
	ArtistID sql.NullString
	PageSize int64
}

type ListAlbumsByAddedDescRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByAddedDesc returns the first page of the available albums by
// (first_seen_at, id), reversed.
func (q *Queries) ListAlbumsByAddedDesc(ctx context.Context, arg ListAlbumsByAddedDescParams) ([]ListAlbumsByAddedDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByAddedDesc, arg.ArtistID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByAddedDescRow
	for rows.Next() {
		var i ListAlbumsByAddedDescRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByAddedDescAfter = `-- name: ListAlbumsByAddedDescAfter :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
  AND (albums.first_seen_at, albums.id) < (CAST(?2 AS INTEGER), CAST(?3 AS TEXT))
ORDER BY albums.first_seen_at DESC, albums.id DESC
LIMIT ?4
`

type ListAlbumsByAddedDescAfterParams struct {
	ArtistID    sql.NullString
	FirstSeenAt int64
	AfterID     string
	PageSize    int64
}

type ListAlbumsByAddedDescAfterRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByAddedDescAfter returns the page of ListAlbumsByAddedDesc
// after the album with that key.
func (q *Queries) ListAlbumsByAddedDescAfter(ctx context.Context, arg ListAlbumsByAddedDescAfterParams) ([]ListAlbumsByAddedDescAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByAddedDescAfter,
		arg.ArtistID,
		arg.FirstSeenAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByAddedDescAfterRow
	for rows.Next() {
		var i ListAlbumsByAddedDescAfterRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByArtistAsc = `-- name: ListAlbumsByArtistAsc :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
ORDER BY albums.artist_key, albums.year_key, albums.title_key, albums.id
LIMIT ?2
`

type ListAlbumsByArtistAscParams struct {
	ArtistID sql.NullString
	PageSize int64
}

type ListAlbumsByArtistAscRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByArtistAsc returns the first page of the available albums by
// (artist_key, year_key, title_key, id), ascending.
func (q *Queries) ListAlbumsByArtistAsc(ctx context.Context, arg ListAlbumsByArtistAscParams) ([]ListAlbumsByArtistAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByArtistAsc, arg.ArtistID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByArtistAscRow
	for rows.Next() {
		var i ListAlbumsByArtistAscRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByArtistAscAfter = `-- name: ListAlbumsByArtistAscAfter :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
  AND (albums.artist_key, albums.year_key, albums.title_key, albums.id) > (CAST(?2 AS BLOB), CAST(?3 AS INTEGER), CAST(?4 AS BLOB), CAST(?5 AS TEXT))
ORDER BY albums.artist_key, albums.year_key, albums.title_key, albums.id
LIMIT ?6
`

type ListAlbumsByArtistAscAfterParams struct {
	ArtistID  sql.NullString
	ArtistKey []byte
	YearKey   int64
	TitleKey  []byte
	AfterID   string
	PageSize  int64
}

type ListAlbumsByArtistAscAfterRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByArtistAscAfter returns the page of ListAlbumsByArtistAsc
// after the album with that key.
func (q *Queries) ListAlbumsByArtistAscAfter(ctx context.Context, arg ListAlbumsByArtistAscAfterParams) ([]ListAlbumsByArtistAscAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByArtistAscAfter,
		arg.ArtistID,
		arg.ArtistKey,
		arg.YearKey,
		arg.TitleKey,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByArtistAscAfterRow
	for rows.Next() {
		var i ListAlbumsByArtistAscAfterRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByArtistDesc = `-- name: ListAlbumsByArtistDesc :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
ORDER BY albums.artist_key DESC, albums.year_key DESC, albums.title_key DESC, albums.id DESC
LIMIT ?2
`

type ListAlbumsByArtistDescParams struct {
	ArtistID sql.NullString
	PageSize int64
}

type ListAlbumsByArtistDescRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByArtistDesc returns the first page of the available albums by
// (artist_key, year_key, title_key, id), reversed.
func (q *Queries) ListAlbumsByArtistDesc(ctx context.Context, arg ListAlbumsByArtistDescParams) ([]ListAlbumsByArtistDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByArtistDesc, arg.ArtistID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByArtistDescRow
	for rows.Next() {
		var i ListAlbumsByArtistDescRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByArtistDescAfter = `-- name: ListAlbumsByArtistDescAfter :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
  AND (albums.artist_key, albums.year_key, albums.title_key, albums.id) < (CAST(?2 AS BLOB), CAST(?3 AS INTEGER), CAST(?4 AS BLOB), CAST(?5 AS TEXT))
ORDER BY albums.artist_key DESC, albums.year_key DESC, albums.title_key DESC, albums.id DESC
LIMIT ?6
`

type ListAlbumsByArtistDescAfterParams struct {
	ArtistID  sql.NullString
	ArtistKey []byte
	YearKey   int64
	TitleKey  []byte
	AfterID   string
	PageSize  int64
}

type ListAlbumsByArtistDescAfterRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByArtistDescAfter returns the page of ListAlbumsByArtistDesc
// after the album with that key.
func (q *Queries) ListAlbumsByArtistDescAfter(ctx context.Context, arg ListAlbumsByArtistDescAfterParams) ([]ListAlbumsByArtistDescAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByArtistDescAfter,
		arg.ArtistID,
		arg.ArtistKey,
		arg.YearKey,
		arg.TitleKey,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByArtistDescAfterRow
	for rows.Next() {
		var i ListAlbumsByArtistDescAfterRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByTitleAsc = `-- name: ListAlbumsByTitleAsc :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
ORDER BY albums.title_key, albums.id
LIMIT ?2
`

type ListAlbumsByTitleAscParams struct {
	ArtistID sql.NullString
	PageSize int64
}

type ListAlbumsByTitleAscRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByTitleAsc returns the first page of the available albums by
// (title_key, id), ascending. In every list of the albums, artist_id, when
// not null, keeps only the albums of that artist, and a Desc order reverses
// every key of the Asc one (DESIGN.md 8.5).
func (q *Queries) ListAlbumsByTitleAsc(ctx context.Context, arg ListAlbumsByTitleAscParams) ([]ListAlbumsByTitleAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByTitleAsc, arg.ArtistID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByTitleAscRow
	for rows.Next() {
		var i ListAlbumsByTitleAscRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByTitleAscAfter = `-- name: ListAlbumsByTitleAscAfter :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
  AND (albums.title_key, albums.id) > (CAST(?2 AS BLOB), CAST(?3 AS TEXT))
ORDER BY albums.title_key, albums.id
LIMIT ?4
`

type ListAlbumsByTitleAscAfterParams struct {
	ArtistID sql.NullString
	TitleKey []byte
	AfterID  string
	PageSize int64
}

type ListAlbumsByTitleAscAfterRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByTitleAscAfter returns the page of ListAlbumsByTitleAsc
// after the album with that key.
func (q *Queries) ListAlbumsByTitleAscAfter(ctx context.Context, arg ListAlbumsByTitleAscAfterParams) ([]ListAlbumsByTitleAscAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByTitleAscAfter,
		arg.ArtistID,
		arg.TitleKey,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByTitleAscAfterRow
	for rows.Next() {
		var i ListAlbumsByTitleAscAfterRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByTitleDesc = `-- name: ListAlbumsByTitleDesc :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
ORDER BY albums.title_key DESC, albums.id DESC
LIMIT ?2
`

type ListAlbumsByTitleDescParams struct {
	ArtistID sql.NullString
	PageSize int64
}

type ListAlbumsByTitleDescRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByTitleDesc returns the first page of the available albums by
// (title_key, id), reversed.
func (q *Queries) ListAlbumsByTitleDesc(ctx context.Context, arg ListAlbumsByTitleDescParams) ([]ListAlbumsByTitleDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByTitleDesc, arg.ArtistID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByTitleDescRow
	for rows.Next() {
		var i ListAlbumsByTitleDescRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByTitleDescAfter = `-- name: ListAlbumsByTitleDescAfter :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
  AND (albums.title_key, albums.id) < (CAST(?2 AS BLOB), CAST(?3 AS TEXT))
ORDER BY albums.title_key DESC, albums.id DESC
LIMIT ?4
`

type ListAlbumsByTitleDescAfterParams struct {
	ArtistID sql.NullString
	TitleKey []byte
	AfterID  string
	PageSize int64
}

type ListAlbumsByTitleDescAfterRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByTitleDescAfter returns the page of ListAlbumsByTitleDesc
// after the album with that key.
func (q *Queries) ListAlbumsByTitleDescAfter(ctx context.Context, arg ListAlbumsByTitleDescAfterParams) ([]ListAlbumsByTitleDescAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByTitleDescAfter,
		arg.ArtistID,
		arg.TitleKey,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByTitleDescAfterRow
	for rows.Next() {
		var i ListAlbumsByTitleDescAfterRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByYearAsc = `-- name: ListAlbumsByYearAsc :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
ORDER BY albums.year_key, albums.title_key, albums.id
LIMIT ?2
`

type ListAlbumsByYearAscParams struct {
	ArtistID sql.NullString
	PageSize int64
}

type ListAlbumsByYearAscRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByYearAsc returns the first page of the available albums by
// (year_key, title_key, id), ascending.
func (q *Queries) ListAlbumsByYearAsc(ctx context.Context, arg ListAlbumsByYearAscParams) ([]ListAlbumsByYearAscRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByYearAsc, arg.ArtistID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByYearAscRow
	for rows.Next() {
		var i ListAlbumsByYearAscRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByYearAscAfter = `-- name: ListAlbumsByYearAscAfter :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
  AND (albums.year_key, albums.title_key, albums.id) > (CAST(?2 AS INTEGER), CAST(?3 AS BLOB), CAST(?4 AS TEXT))
ORDER BY albums.year_key, albums.title_key, albums.id
LIMIT ?5
`

type ListAlbumsByYearAscAfterParams struct {
	ArtistID sql.NullString
	YearKey  int64
	TitleKey []byte
	AfterID  string
	PageSize int64
}

type ListAlbumsByYearAscAfterRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByYearAscAfter returns the page of ListAlbumsByYearAsc
// after the album with that key.
func (q *Queries) ListAlbumsByYearAscAfter(ctx context.Context, arg ListAlbumsByYearAscAfterParams) ([]ListAlbumsByYearAscAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByYearAscAfter,
		arg.ArtistID,
		arg.YearKey,
		arg.TitleKey,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByYearAscAfterRow
	for rows.Next() {
		var i ListAlbumsByYearAscAfterRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByYearDesc = `-- name: ListAlbumsByYearDesc :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
ORDER BY albums.year_key DESC, albums.title_key DESC, albums.id DESC
LIMIT ?2
`

type ListAlbumsByYearDescParams struct {
	ArtistID sql.NullString
	PageSize int64
}

type ListAlbumsByYearDescRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByYearDesc returns the first page of the available albums by
// (year_key, title_key, id), reversed.
func (q *Queries) ListAlbumsByYearDesc(ctx context.Context, arg ListAlbumsByYearDescParams) ([]ListAlbumsByYearDescRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByYearDesc, arg.ArtistID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByYearDescRow
	for rows.Next() {
		var i ListAlbumsByYearDescRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByYearDescAfter = `-- name: ListAlbumsByYearDescAfter :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.available = 1
  AND (CAST(?1 AS TEXT) IS NULL OR albums.artist_id = CAST(?1 AS TEXT))
  AND (albums.year_key, albums.title_key, albums.id) < (CAST(?2 AS INTEGER), CAST(?3 AS BLOB), CAST(?4 AS TEXT))
ORDER BY albums.year_key DESC, albums.title_key DESC, albums.id DESC
LIMIT ?5
`

type ListAlbumsByYearDescAfterParams struct {
	ArtistID sql.NullString
	YearKey  int64
	TitleKey []byte
	AfterID  string
	PageSize int64
}

type ListAlbumsByYearDescAfterRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsByYearDescAfter returns the page of ListAlbumsByYearDesc
// after the album with that key.
func (q *Queries) ListAlbumsByYearDescAfter(ctx context.Context, arg ListAlbumsByYearDescAfterParams) ([]ListAlbumsByYearDescAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsByYearDescAfter,
		arg.ArtistID,
		arg.YearKey,
		arg.TitleKey,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsByYearDescAfterRow
	for rows.Next() {
		var i ListAlbumsByYearDescAfterRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsOfArtist = `-- name: ListAlbumsOfArtist :many
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums INDEXED BY albums_artist_id_idx
JOIN artists ON artists.id = albums.artist_id
WHERE albums.artist_id = ?1 AND albums.available = 1
ORDER BY albums.year_key, albums.title_key, albums.id
`

type ListAlbumsOfArtistRow struct {
	Album      Album
	ArtistName string
}

// ListAlbumsOfArtist returns every available album of an artist, by
// (year_key, title_key, id): the order of the albums of one artist in the
// list by artist. Without INDEXED BY, SQLite walks every available album in
// the order of albums_year_idx to avoid sorting the few of one artist.
func (q *Queries) ListAlbumsOfArtist(ctx context.Context, artistID string) ([]ListAlbumsOfArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsOfArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsOfArtistRow
	for rows.Next() {
		var i ListAlbumsOfArtistRow
		if err := rows.Scan(
			&i.Album.Seq,
			&i.Album.ID,
			&i.Album.ArtistID,
			&i.Album.ArtistKey,
			&i.Album.Title,
			&i.Album.TitleKey,
			&i.Album.Year,
			&i.Album.YearKey,
			&i.Album.Genre,
			&i.Album.Compilation,
			&i.Album.RelPath,
			&i.Album.AlbumRevision,
			&i.Album.RenderVersion,
			&i.Album.ReceiptHash,
			&i.Album.CoverRel,
			&i.Album.CoverSha256,
			&i.Album.CoverMime,
			&i.Album.CoverSize,
			&i.Album.CoverMtimeNs,
			&i.Album.TrackCount,
			&i.Album.DurationMs,
			&i.Album.Available,
			&i.Album.FirstSeenAt,
			&i.Album.UpdatedAt,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistsByName = `-- name: ListArtistsByName :many
SELECT artists.seq, artists.id, artists.name, artists.sort_key,
    (SELECT count(*) FROM albums
     WHERE albums.artist_id = artists.id AND albums.available = 1) AS album_count
FROM artists
WHERE EXISTS (SELECT 1 FROM albums WHERE albums.artist_id = artists.id AND albums.available = 1)
ORDER BY artists.sort_key, artists.id
LIMIT ?1
`

type ListArtistsByNameRow struct {
	Artist     Artist
	AlbumCount int64
}

// ListArtistsByName returns the first page of the artists that have at
// least one available album, by (sort_key, id), with how many they have
// (DESIGN.md 8.5). Like every list of the catalog it is paginated by key,
// never by OFFSET: the query of each page after the first compares the key
// of the rows with the key of the cursor as one row value, which SQLite
// turns into a range of the index of the order (T9). The values of the
// cursor are cast to the type of their column: a blob is greater than any
// text in SQLite, and sqlc would bind an id as a blob.
func (q *Queries) ListArtistsByName(ctx context.Context, pageSize int64) ([]ListArtistsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtistsByName, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtistsByNameRow
	for rows.Next() {
		var i ListArtistsByNameRow
		if err := rows.Scan(
			&i.Artist.Seq,
			&i.Artist.ID,
			&i.Artist.Name,
			&i.Artist.SortKey,
			&i.AlbumCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtistsByNameAfter = `-- name: ListArtistsByNameAfter :many
SELECT artists.seq, artists.id, artists.name, artists.sort_key,
    (SELECT count(*) FROM albums
     WHERE albums.artist_id = artists.id AND albums.available = 1) AS album_count
FROM artists
WHERE EXISTS (SELECT 1 FROM albums WHERE albums.artist_id = artists.id AND albums.available = 1)
  AND (artists.sort_key, artists.id) > (CAST(?1 AS BLOB), CAST(?2 AS TEXT))
ORDER BY artists.sort_key, artists.id
LIMIT ?3
`

type ListArtistsByNameAfterParams struct {
	SortKey  []byte
	AfterID  string
	PageSize int64
}

type ListArtistsByNameAfterRow struct {
	Artist     Artist
	AlbumCount int64
}

// ListArtistsByNameAfter returns the page of ListArtistsByName after the
// artist with that key.
func (q *Queries) ListArtistsByNameAfter(ctx context.Context, arg ListArtistsByNameAfterParams) ([]ListArtistsByNameAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listArtistsByNameAfter, arg.SortKey, arg.AfterID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtistsByNameAfterRow
	for rows.Next() {
		var i ListArtistsByNameAfterRow
		if err := rows.Scan(
			&i.Artist.Seq,
			&i.Artist.ID,
			&i.Artist.Name,
			&i.Artist.SortKey,
			&i.AlbumCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailableTracksOfAlbum = `-- name: ListAvailableTracksOfAlbum :many
SELECT tracks.seq, tracks.id, tracks.album_id, tracks.fingerprint, tracks.fp_version, tracks.occurrence, tracks.disc, tracks."no", tracks.title, tracks.artist, tracks.genre, tracks.rel_path, tracks.file_size, tracks.file_mtime_ns, tracks.file_sha256, tracks.codec, tracks.sample_rate, tracks.channels, tracks.bit_depth, tracks.bitrate, tracks.duration_ms, tracks.lyrics_rel, tracks.lyrics_sha256, tracks.rg_track_gain, tracks.rg_track_peak, tracks.rg_album_gain, tracks.rg_album_peak, tracks.available, tracks.updated_at,
    EXISTS (SELECT 1 FROM favorites
            WHERE favorites.user_id = ?1 AND favorites.track_id = tracks.id) AS favorite
FROM tracks
WHERE tracks.album_id = ?2 AND tracks.available = 1
ORDER BY tracks.disc, tracks."no", tracks.seq
`

type ListAvailableTracksOfAlbumParams struct {
	UserID  string
	AlbumID string
}

type ListAvailableTracksOfAlbumRow struct {
	Track    Track
	Favorite bool
}

// ListAvailableTracksOfAlbum returns the available tracks of an album by
// (disc, no), then in the order the rows were created, and whether each is
// a favorite of the user.
func (q *Queries) ListAvailableTracksOfAlbum(ctx context.Context, arg ListAvailableTracksOfAlbumParams) ([]ListAvailableTracksOfAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, listAvailableTracksOfAlbum, arg.UserID, arg.AlbumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableTracksOfAlbumRow
	for rows.Next() {
		var i ListAvailableTracksOfAlbumRow
		if err := rows.Scan(
			&i.Track.Seq,
			&i.Track.ID,
			&i.Track.AlbumID,
			&i.Track.Fingerprint,
			&i.Track.FpVersion,
			&i.Track.Occurrence,
			&i.Track.Disc,
			&i.Track.No,
			&i.Track.Title,
			&i.Track.Artist,
			&i.Track.Genre,
			&i.Track.RelPath,
			&i.Track.FileSize,
			&i.Track.FileMtimeNs,
			&i.Track.FileSha256,
			&i.Track.Codec,
			&i.Track.SampleRate,
			&i.Track.Channels,
			&i.Track.BitDepth,
			&i.Track.Bitrate,
			&i.Track.DurationMs,
			&i.Track.LyricsRel,
			&i.Track.LyricsSha256,
			&i.Track.RgTrackGain,
			&i.Track.RgTrackPeak,
			&i.Track.RgAlbumGain,
			&i.Track.RgAlbumPeak,
			&i.Track.Available,
			&i.Track.UpdatedAt,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
