// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package store

import (
	"context"
	"database/sql"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, track_id, created_at)
SELECT users.id, CAST(?1 AS text), CAST(?2 AS integer)
FROM users
WHERE users.id = ?3
ON CONFLICT (user_id, track_id) DO NOTHING
`

type AddFavoriteParams struct {
	TrackID   string
	CreatedAt int64
	UserID    string
}

// AddFavorite makes a track a favorite of a user since that moment. A track
// that is one already keeps the row it has, with its moment (DESIGN.md
// 8.3: idempotent). The row is read from users, so that an account deleted
// since its request was authenticated adds nothing instead of failing on
// the foreign key. The caller checks the track with TrackExists in the same
// transaction.
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, addFavorite, arg.TrackID, arg.CreatedAt, arg.UserID)
	return err
}

const listFavorites = `-- name: ListFavorites :many
SELECT favorites.created_at AS favorited_at, tracks.seq, tracks.id, tracks.album_id, tracks.fingerprint, tracks.fp_version, tracks.occurrence, tracks.disc, tracks."no", tracks.title, tracks.artist, tracks.genre, tracks.rel_path, tracks.file_size, tracks.file_mtime_ns, tracks.file_sha256, tracks.codec, tracks.sample_rate, tracks.channels, tracks.bit_depth, tracks.bitrate, tracks.duration_ms, tracks.lyrics_rel, tracks.lyrics_sha256, tracks.rg_track_gain, tracks.rg_track_peak, tracks.rg_album_gain, tracks.rg_album_peak, tracks.available, tracks.updated_at, tracks.title_key, tracks.artist_key, tracks.album_key, tracks.first_seen_at,
    albums.title AS album_title, albums.year AS album_year, albums.cover_sha256 AS album_cover_sha256,
    albums.artist_id AS album_artist_id, artists.name AS album_artist_name,
    EXISTS (SELECT 1 FROM favorites AS mine
            WHERE mine.user_id = ?1 AND mine.track_id = tracks.id) AS favorite
FROM favorites
JOIN tracks ON tracks.id = favorites.track_id
JOIN albums ON albums.id = tracks.album_id
JOIN artists ON artists.id = albums.artist_id
WHERE favorites.user_id = ?1
ORDER BY favorites.created_at DESC, favorites.track_id DESC
LIMIT ?2
`

type ListFavoritesParams struct {
	UserID   string
	PageSize int64
}

type ListFavoritesRow struct {
	FavoritedAt      int64
	Track            Track
	AlbumTitle       string
	AlbumYear        sql.NullInt64
	AlbumCoverSha256 sql.NullString
	AlbumArtistID    string
	AlbumArtistName  string
	Favorite         bool
}

// ListFavorites returns the first page of the favorites of a user, the most
// recent first: by (created_at, track_id), reversed (DESIGN.md 8.5), on the
// index favorites_user_created_idx. A track that is not available is
// listed, with what the API shows of its album, like GetTrackWithAlbum.
// favorite is computed as in every other query that returns a track, not
// taken for granted.
func (q *Queries) ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error) {
	rows, err := q.db.QueryContext(ctx, listFavorites, arg.UserID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesRow
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.FavoritedAt,
			&i.Track.Seq,
			&i.Track.ID,
			&i.Track.AlbumID,
			&i.Track.Fingerprint,
			&i.Track.FpVersion,
			&i.Track.Occurrence,
			&i.Track.Disc,
			&i.Track.No,
			&i.Track.Title,
			&i.Track.Artist,
			&i.Track.Genre,
			&i.Track.RelPath,
			&i.Track.FileSize,
			&i.Track.FileMtimeNs,
			&i.Track.FileSha256,
			&i.Track.Codec,
			&i.Track.SampleRate,
			&i.Track.Channels,
			&i.Track.BitDepth,
			&i.Track.Bitrate,
			&i.Track.DurationMs,
			&i.Track.LyricsRel,
			&i.Track.LyricsSha256,
			&i.Track.RgTrackGain,
			&i.Track.RgTrackPeak,
			&i.Track.RgAlbumGain,
			&i.Track.RgAlbumPeak,
			&i.Track.Available,
			&i.Track.UpdatedAt,
			&i.Track.TitleKey,
			&i.Track.ArtistKey,
			&i.Track.AlbumKey,
			&i.Track.FirstSeenAt,
			&i.AlbumTitle,
			&i.AlbumYear,
			&i.AlbumCoverSha256,
			&i.AlbumArtistID,
			&i.AlbumArtistName,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoritesAfter = `-- name: ListFavoritesAfter :many
SELECT favorites.created_at AS favorited_at, tracks.seq, tracks.id, tracks.album_id, tracks.fingerprint, tracks.fp_version, tracks.occurrence, tracks.disc, tracks."no", tracks.title, tracks.artist, tracks.genre, tracks.rel_path, tracks.file_size, tracks.file_mtime_ns, tracks.file_sha256, tracks.codec, tracks.sample_rate, tracks.channels, tracks.bit_depth, tracks.bitrate, tracks.duration_ms, tracks.lyrics_rel, tracks.lyrics_sha256, tracks.rg_track_gain, tracks.rg_track_peak, tracks.rg_album_gain, tracks.rg_album_peak, tracks.available, tracks.updated_at, tracks.title_key, tracks.artist_key, tracks.album_key, tracks.first_seen_at,
    albums.title AS album_title, albums.year AS album_year, albums.cover_sha256 AS album_cover_sha256,
    albums.artist_id AS album_artist_id, artists.name AS album_artist_name,
    EXISTS (SELECT 1 FROM favorites AS mine
            WHERE mine.user_id = ?1 AND mine.track_id = tracks.id) AS favorite
FROM favorites
JOIN tracks ON tracks.id = favorites.track_id
JOIN albums ON albums.id = tracks.album_id
JOIN artists ON artists.id = albums.artist_id
WHERE favorites.user_id = ?1
  AND (favorites.created_at, favorites.track_id) < (CAST(?2 AS INTEGER), CAST(?3 AS TEXT))
ORDER BY favorites.created_at DESC, favorites.track_id DESC
LIMIT ?4
`

type ListFavoritesAfterParams struct {
	UserID    string
	CreatedAt int64
	AfterID   string
	PageSize  int64
}

type ListFavoritesAfterRow struct {
	FavoritedAt      int64
	Track            Track
	AlbumTitle       string
	AlbumYear        sql.NullInt64
	AlbumCoverSha256 sql.NullString
	AlbumArtistID    string
	AlbumArtistName  string
	Favorite         bool
}

// ListFavoritesAfter returns the page of ListFavorites after the favorite
// with that key. The values of the cursor are cast to the type of their
// column, as in the lists of the catalog.
func (q *Queries) ListFavoritesAfter(ctx context.Context, arg ListFavoritesAfterParams) ([]ListFavoritesAfterRow, error) {
	rows, err := q.db.QueryContext(ctx, listFavoritesAfter,
		arg.UserID,
		arg.CreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesAfterRow
	for rows.Next() {
		var i ListFavoritesAfterRow
		if err := rows.Scan(
			&i.FavoritedAt,
			&i.Track.Seq,
			&i.Track.ID,
			&i.Track.AlbumID,
			&i.Track.Fingerprint,
			&i.Track.FpVersion,
			&i.Track.Occurrence,
			&i.Track.Disc,
			&i.Track.No,
			&i.Track.Title,
			&i.Track.Artist,
			&i.Track.Genre,
			&i.Track.RelPath,
			&i.Track.FileSize,
			&i.Track.FileMtimeNs,
			&i.Track.FileSha256,
			&i.Track.Codec,
			&i.Track.SampleRate,
			&i.Track.Channels,
			&i.Track.BitDepth,
			&i.Track.Bitrate,
			&i.Track.DurationMs,
			&i.Track.LyricsRel,
			&i.Track.LyricsSha256,
			&i.Track.RgTrackGain,
			&i.Track.RgTrackPeak,
			&i.Track.RgAlbumGain,
			&i.Track.RgAlbumPeak,
			&i.Track.Available,
			&i.Track.UpdatedAt,
			&i.Track.TitleKey,
			&i.Track.ArtistKey,
			&i.Track.AlbumKey,
			&i.Track.FirstSeenAt,
			&i.AlbumTitle,
			&i.AlbumYear,
			&i.AlbumCoverSha256,
			&i.AlbumArtistID,
			&i.AlbumArtistName,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites WHERE user_id = ?1 AND track_id = ?2
`

type RemoveFavoriteParams struct {
	UserID  string
	TrackID string
}

// RemoveFavorite makes a track no longer a favorite of a user. A track that
// is not one changes nothing.
func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.ExecContext(ctx, removeFavorite, arg.UserID, arg.TrackID)
	return err
}

const trackExists = `-- name: TrackExists :one
SELECT EXISTS (SELECT 1 FROM tracks WHERE tracks.id = ?1) AS found
`

// TrackExists tells whether there is a track with that id, available or
// not. The rows of tracks are never deleted (I3), so a track that exists
// once exists for ever.
func (q *Queries) TrackExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, trackExists, id)
	var found bool
	err := row.Scan(&found)
	return found, err
}
