// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package store

import (
	"context"
)

const countRows = `-- name: CountRows :one
SELECT
    (SELECT count(*) FROM users) AS users,
    (SELECT count(*) FROM playlists) AS playlists,
    (SELECT count(*) FROM playlist_items) AS playlist_items,
    (SELECT count(*) FROM favorites) AS favorites,
    (SELECT count(*) FROM artists) AS artists,
    (SELECT count(*) FROM albums) AS albums,
    (SELECT count(*) FROM tracks) AS tracks
`

type CountRowsRow struct {
	Users         int64
	Playlists     int64
	PlaylistItems int64
	Favorites     int64
	Artists       int64
	Albums        int64
	Tracks        int64
}

// CountRows counts the rows of the tables a backup names in its manifest
// (DESIGN.md 11.4): what a reader of the manifest can compare with what the
// restored server shows.
func (q *Queries) CountRows(ctx context.Context) (CountRowsRow, error) {
	row := q.db.QueryRowContext(ctx, countRows)
	var i CountRowsRow
	err := row.Scan(
		&i.Users,
		&i.Playlists,
		&i.PlaylistItems,
		&i.Favorites,
		&i.Artists,
		&i.Albums,
		&i.Tracks,
	)
	return i, err
}

const listAlbumsWithWrongCounters = `-- name: ListAlbumsWithWrongCounters :many
SELECT albums.id, albums.track_count, albums.duration_ms,
    count(tracks.seq) AS available_tracks,
    CAST(coalesce(sum(tracks.duration_ms), 0) AS INTEGER) AS available_duration_ms
FROM albums
LEFT JOIN tracks INDEXED BY tracks_album_disc_no_idx ON tracks.album_id = albums.id AND tracks.available = 1
GROUP BY albums.seq
HAVING albums.track_count <> count(tracks.seq)
    OR albums.duration_ms <> coalesce(sum(tracks.duration_ms), 0)
ORDER BY albums.seq
`

type ListAlbumsWithWrongCountersRow struct {
	ID                  string
	TrackCount          int64
	DurationMs          int64
	AvailableTracks     int64
	AvailableDurationMs int64
}

// ListAlbumsWithWrongCounters returns the albums whose track_count or
// duration_ms is not what their available tracks say (DESIGN.md 5.2), with
// both. The doctor reads it (DESIGN.md 11.4); a sound index has none.
func (q *Queries) ListAlbumsWithWrongCounters(ctx context.Context) ([]ListAlbumsWithWrongCountersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlbumsWithWrongCounters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlbumsWithWrongCountersRow
	for rows.Next() {
		var i ListAlbumsWithWrongCountersRow
		if err := rows.Scan(
			&i.ID,
			&i.TrackCount,
			&i.DurationMs,
			&i.AvailableTracks,
			&i.AvailableDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
