// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meta.sql

package store

import (
	"context"
)

const getMeta = `-- name: GetMeta :one
SELECT value FROM meta WHERE "key" = ?
`

// GetMeta returns what the server remembers about itself under a key, such
// as 'ffmpeg_version' or 'collate_version' (DESIGN.md 5.2). A key that was
// never set is sql.ErrNoRows.
func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setMeta = `-- name: SetMeta :exec
INSERT INTO meta ("key", value) VALUES (?, ?)
ON CONFLICT ("key") DO UPDATE SET value = excluded.value
`

type SetMetaParams struct {
	Key   string
	Value string
}

// SetMeta sets the value of a key, new or not.
func (q *Queries) SetMeta(ctx context.Context, arg SetMetaParams) error {
	_, err := q.db.ExecContext(ctx, setMeta, arg.Key, arg.Value)
	return err
}
