// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type Album struct {
	Seq           int64
	ID            string
	ArtistID      string
	ArtistKey     []byte
	Title         string
	TitleKey      []byte
	Year          sql.NullInt64
	YearKey       int64
	Genre         sql.NullString
	Compilation   int64
	RelPath       string
	AlbumRevision int64
	RenderVersion string
	ReceiptHash   string
	CoverRel      sql.NullString
	CoverSha256   sql.NullString
	CoverMime     sql.NullString
	CoverSize     sql.NullInt64
	CoverMtimeNs  sql.NullInt64
	TrackCount    int64
	DurationMs    int64
	Available     int64
	FirstSeenAt   int64
	UpdatedAt     int64
}

type Artist struct {
	Seq     int64
	ID      string
	Name    string
	SortKey []byte
}

type Favorite struct {
	UserID    string
	TrackID   string
	CreatedAt int64
}

type Meta struct {
	Key   string
	Value string
}

type Playlist struct {
	ID          string
	UserID      string
	Name        string
	Description string
	Revision    int64
	CreatedAt   int64
	UpdatedAt   int64
}

type PlaylistItem struct {
	ID         string
	PlaylistID string
	TrackID    string
	Position   int64
	AddedAt    int64
}

type Session struct {
	ID         string
	TokenHash  string
	UserID     string
	Kind       string
	DeviceName sql.NullString
	CreatedAt  int64
	LastUsedAt int64
	ExpiresAt  int64
}

type Track struct {
	Seq          int64
	ID           string
	AlbumID      string
	Fingerprint  string
	FpVersion    string
	Occurrence   int64
	Disc         int64
	No           int64
	Title        string
	Artist       string
	Genre        sql.NullString
	RelPath      string
	FileSize     int64
	FileMtimeNs  int64
	FileSha256   string
	Codec        string
	SampleRate   int64
	Channels     int64
	BitDepth     sql.NullInt64
	Bitrate      sql.NullInt64
	DurationMs   sql.NullInt64
	LyricsRel    sql.NullString
	LyricsSha256 sql.NullString
	RgTrackGain  sql.NullFloat64
	RgTrackPeak  sql.NullFloat64
	RgAlbumGain  sql.NullFloat64
	RgAlbumPeak  sql.NullFloat64
	Available    int64
	UpdatedAt    int64
}

type User struct {
	ID                string
	Username          string
	PasswordHash      string
	Role              string
	Disabled          int64
	CreatedAt         int64
	PasswordChangedAt int64
}
