// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlists.sql

package store

import (
	"context"
	"database/sql"
)

const countPlaylistsOfUser = `-- name: CountPlaylistsOfUser :one
SELECT count(*) FROM playlists WHERE user_id = ?
`

// CountPlaylistsOfUser counts the playlists of a user, for the limit of
// DESIGN.md 5.2.
func (q *Queries) CountPlaylistsOfUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaylistsOfUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlaylist = `-- name: CreatePlaylist :execrows
INSERT INTO playlists (id, user_id, name, description, revision, created_at, updated_at)
SELECT CAST(?1 AS text), users.id, CAST(?2 AS text), CAST(?3 AS text), 1,
    CAST(?4 AS integer), CAST(?4 AS integer)
FROM users
WHERE users.id = ?5
`

type CreatePlaylistParams struct {
	ID          string
	Name        string
	Description string
	CreatedAt   int64
	UserID      string
}

// CreatePlaylist writes an empty playlist of a user, at its first revision.
// The owner is read from users, so that an account deleted since its request
// was authenticated creates nothing (no row is written) instead of failing
// on the foreign key.
func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createPlaylist,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists WHERE id = ?
`

// DeletePlaylist deletes a playlist; its items go with it (ON DELETE
// CASCADE).
func (q *Queries) DeletePlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, id)
	return err
}

const deletePlaylistItem = `-- name: DeletePlaylistItem :exec
DELETE FROM playlist_items WHERE id = ?
`

// DeletePlaylistItem removes an item. RenumberPlaylistItems then closes the
// place it left.
func (q *Queries) DeletePlaylistItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePlaylistItem, id)
	return err
}

const getPlaylistItemPosition = `-- name: GetPlaylistItemPosition :one
SELECT position FROM playlist_items WHERE id = ?1 AND playlist_id = ?2
`

type GetPlaylistItemPositionParams struct {
	ID         string
	PlaylistID string
}

// GetPlaylistItemPosition returns where an item of a playlist is. An item
// that the playlist does not have, one of another playlist included, is
// sql.ErrNoRows.
func (q *Queries) GetPlaylistItemPosition(ctx context.Context, arg GetPlaylistItemPositionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistItemPosition, arg.ID, arg.PlaylistID)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const getPlaylistOfUser = `-- name: GetPlaylistOfUser :one
SELECT playlists.id, playlists.user_id, playlists.name, playlists.description, playlists.revision, playlists.created_at, playlists.updated_at,
    (SELECT count(*) FROM playlist_items
     WHERE playlist_items.playlist_id = playlists.id) AS item_count,
    CAST((SELECT coalesce(sum(tracks.duration_ms), 0)
          FROM playlist_items
          JOIN tracks ON tracks.id = playlist_items.track_id
          WHERE playlist_items.playlist_id = playlists.id AND tracks.available = 1) AS INTEGER) AS duration_ms
FROM playlists
WHERE playlists.id = ?1 AND playlists.user_id = ?2
`

type GetPlaylistOfUserParams struct {
	ID     string
	UserID string
}

type GetPlaylistOfUserRow struct {
	Playlist   Playlist
	ItemCount  int64
	DurationMs int64
}

// GetPlaylistOfUser returns a playlist of a user with what is computed from
// its items: item_count counts every item, and duration_ms adds up only the
// tracks that are available (DESIGN.md, erratum of 2026-10-04). A playlist
// that does not exist, or is of another user, is sql.ErrNoRows.
//
// A playlist is read and changed only through this query,
// GetPlaylistStateOfUser and ListPlaylistsOfUser, which name its owner: the
// playlist of another user is a row that is not found (DESIGN.md 8.6, I6).
// The other queries of this file run in the transaction that read the
// playlist that way.
func (q *Queries) GetPlaylistOfUser(ctx context.Context, arg GetPlaylistOfUserParams) (GetPlaylistOfUserRow, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistOfUser, arg.ID, arg.UserID)
	var i GetPlaylistOfUserRow
	err := row.Scan(
		&i.Playlist.ID,
		&i.Playlist.UserID,
		&i.Playlist.Name,
		&i.Playlist.Description,
		&i.Playlist.Revision,
		&i.Playlist.CreatedAt,
		&i.Playlist.UpdatedAt,
		&i.ItemCount,
		&i.DurationMs,
	)
	return i, err
}

const getPlaylistStateOfUser = `-- name: GetPlaylistStateOfUser :one
SELECT playlists.id, playlists.user_id, playlists.name, playlists.description, playlists.revision, playlists.created_at, playlists.updated_at,
    (SELECT count(*) FROM playlist_items
     WHERE playlist_items.playlist_id = playlists.id) AS item_count
FROM playlists
WHERE playlists.id = ?1 AND playlists.user_id = ?2
`

type GetPlaylistStateOfUserParams struct {
	ID     string
	UserID string
}

type GetPlaylistStateOfUserRow struct {
	Playlist  Playlist
	ItemCount int64
}

// GetPlaylistStateOfUser returns a playlist of a user and how many items it
// has, without the duration of GetPlaylistOfUser, which reads the track of
// every item: what a change needs of the playlist before it changes it, and
// what a page of its items needs, the revision. A playlist that does not
// exist, or is of another user, is sql.ErrNoRows.
func (q *Queries) GetPlaylistStateOfUser(ctx context.Context, arg GetPlaylistStateOfUserParams) (GetPlaylistStateOfUserRow, error) {
	row := q.db.QueryRowContext(ctx, getPlaylistStateOfUser, arg.ID, arg.UserID)
	var i GetPlaylistStateOfUserRow
	err := row.Scan(
		&i.Playlist.ID,
		&i.Playlist.UserID,
		&i.Playlist.Name,
		&i.Playlist.Description,
		&i.Playlist.Revision,
		&i.Playlist.CreatedAt,
		&i.Playlist.UpdatedAt,
		&i.ItemCount,
	)
	return i, err
}

const getTrackAvailability = `-- name: GetTrackAvailability :one
SELECT available FROM tracks WHERE id = ?
`

// GetTrackAvailability tells whether a track is available. A track that
// does not exist is sql.ErrNoRows.
func (q *Queries) GetTrackAvailability(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTrackAvailability, id)
	var available int64
	err := row.Scan(&available)
	return available, err
}

const insertPlaylistItem = `-- name: InsertPlaylistItem :exec
INSERT INTO playlist_items (id, playlist_id, track_id, position, added_at) VALUES (?, ?, ?, ?, ?)
`

type InsertPlaylistItemParams struct {
	ID         string
	PlaylistID string
	TrackID    string
	Position   int64
	AddedAt    int64
}

// InsertPlaylistItem writes a new item of a playlist.
func (q *Queries) InsertPlaylistItem(ctx context.Context, arg InsertPlaylistItemParams) error {
	_, err := q.db.ExecContext(ctx, insertPlaylistItem,
		arg.ID,
		arg.PlaylistID,
		arg.TrackID,
		arg.Position,
		arg.AddedAt,
	)
	return err
}

const listPlaylistItems = `-- name: ListPlaylistItems :many
SELECT playlist_items.id AS item_id, playlist_items.position, playlist_items.added_at, tracks.seq, tracks.id, tracks.album_id, tracks.fingerprint, tracks.fp_version, tracks.occurrence, tracks.disc, tracks."no", tracks.title, tracks.artist, tracks.genre, tracks.rel_path, tracks.file_size, tracks.file_mtime_ns, tracks.file_sha256, tracks.codec, tracks.sample_rate, tracks.channels, tracks.bit_depth, tracks.bitrate, tracks.duration_ms, tracks.lyrics_rel, tracks.lyrics_sha256, tracks.rg_track_gain, tracks.rg_track_peak, tracks.rg_album_gain, tracks.rg_album_peak, tracks.available, tracks.updated_at,
    albums.title AS album_title, albums.year AS album_year, albums.cover_sha256 AS album_cover_sha256,
    albums.artist_id AS album_artist_id, artists.name AS album_artist_name,
    EXISTS (SELECT 1 FROM favorites AS mine
            WHERE mine.user_id = ?1 AND mine.track_id = tracks.id) AS favorite
FROM playlist_items
JOIN tracks ON tracks.id = playlist_items.track_id
JOIN albums ON albums.id = tracks.album_id
JOIN artists ON artists.id = albums.artist_id
WHERE playlist_items.playlist_id = ?2
  AND (playlist_items.position, playlist_items.id) > (CAST(?3 AS INTEGER), CAST(?4 AS TEXT))
ORDER BY playlist_items.position, playlist_items.id
LIMIT ?5
`

type ListPlaylistItemsParams struct {
	UserID        string
	PlaylistID    string
	AfterPosition int64
	AfterID       string
	PageSize      int64
}

type ListPlaylistItemsRow struct {
	ItemID           string
	Position         int64
	AddedAt          int64
	Track            Track
	AlbumTitle       string
	AlbumYear        sql.NullInt64
	AlbumCoverSha256 sql.NullString
	AlbumArtistID    string
	AlbumArtistName  string
	Favorite         bool
}

// ListPlaylistItems returns a page of the items of a playlist, by
// (position, id) (DESIGN.md 8.5), on the index playlist_items_position_idx:
// the items after the one with that key, which need not exist any more. No
// position is negative, so the first page is the one after (-1, ”). The
// values of the cursor are cast to the type of their column, as in the
// lists of the catalog. A track that is not available is listed, with what
// the API shows of its album, like GetTrackWithAlbum. favorite is computed
// as in every other query that returns a track.
func (q *Queries) ListPlaylistItems(ctx context.Context, arg ListPlaylistItemsParams) ([]ListPlaylistItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistItems,
		arg.UserID,
		arg.PlaylistID,
		arg.AfterPosition,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistItemsRow
	for rows.Next() {
		var i ListPlaylistItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Position,
			&i.AddedAt,
			&i.Track.Seq,
			&i.Track.ID,
			&i.Track.AlbumID,
			&i.Track.Fingerprint,
			&i.Track.FpVersion,
			&i.Track.Occurrence,
			&i.Track.Disc,
			&i.Track.No,
			&i.Track.Title,
			&i.Track.Artist,
			&i.Track.Genre,
			&i.Track.RelPath,
			&i.Track.FileSize,
			&i.Track.FileMtimeNs,
			&i.Track.FileSha256,
			&i.Track.Codec,
			&i.Track.SampleRate,
			&i.Track.Channels,
			&i.Track.BitDepth,
			&i.Track.Bitrate,
			&i.Track.DurationMs,
			&i.Track.LyricsRel,
			&i.Track.LyricsSha256,
			&i.Track.RgTrackGain,
			&i.Track.RgTrackPeak,
			&i.Track.RgAlbumGain,
			&i.Track.RgAlbumPeak,
			&i.Track.Available,
			&i.Track.UpdatedAt,
			&i.AlbumTitle,
			&i.AlbumYear,
			&i.AlbumCoverSha256,
			&i.AlbumArtistID,
			&i.AlbumArtistName,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistsOfUser = `-- name: ListPlaylistsOfUser :many
SELECT playlists.id, playlists.user_id, playlists.name, playlists.description, playlists.revision, playlists.created_at, playlists.updated_at,
    (SELECT count(*) FROM playlist_items
     WHERE playlist_items.playlist_id = playlists.id) AS item_count,
    CAST((SELECT coalesce(sum(tracks.duration_ms), 0)
          FROM playlist_items
          JOIN tracks ON tracks.id = playlist_items.track_id
          WHERE playlist_items.playlist_id = playlists.id AND tracks.available = 1) AS INTEGER) AS duration_ms
FROM playlists
WHERE playlists.user_id = ?1
ORDER BY playlists.created_at, playlists.id
`

type ListPlaylistsOfUserRow struct {
	Playlist   Playlist
	ItemCount  int64
	DurationMs int64
}

// ListPlaylistsOfUser returns every playlist of a user as GetPlaylistOfUser
// does, the oldest first. A user has at most 500.
func (q *Queries) ListPlaylistsOfUser(ctx context.Context, userID string) ([]ListPlaylistsOfUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaylistsOfUserRow
	for rows.Next() {
		var i ListPlaylistsOfUserRow
		if err := rows.Scan(
			&i.Playlist.ID,
			&i.Playlist.UserID,
			&i.Playlist.Name,
			&i.Playlist.Description,
			&i.Playlist.Revision,
			&i.Playlist.CreatedAt,
			&i.Playlist.UpdatedAt,
			&i.ItemCount,
			&i.DurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renamePlaylist = `-- name: RenamePlaylist :exec
UPDATE playlists
SET name = ?1, description = ?2, revision = revision + 1, updated_at = ?3
WHERE id = ?4
`

type RenamePlaylistParams struct {
	Name        string
	Description string
	UpdatedAt   int64
	ID          string
}

// RenamePlaylist gives a playlist its name and its description, and a new
// revision (DESIGN.md 8.6). A change of the items uses TouchPlaylist.
func (q *Queries) RenamePlaylist(ctx context.Context, arg RenamePlaylistParams) error {
	_, err := q.db.ExecContext(ctx, renamePlaylist,
		arg.Name,
		arg.Description,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const renumberPlaylistItems = `-- name: RenumberPlaylistItems :exec
INSERT INTO playlist_items (id, playlist_id, track_id, position, added_at)
SELECT items.id, items.playlist_id, items.track_id,
    row_number() OVER (ORDER BY items.position, items.id) - 1, items.added_at
FROM playlist_items AS items
WHERE items.playlist_id = ?1
  AND (SELECT count(*) <> count(DISTINCT placed.position) OR max(placed.position) <> count(*) - 1
       FROM playlist_items AS placed
       WHERE placed.playlist_id = ?1)
ON CONFLICT (id) DO UPDATE SET position = excluded.position
WHERE playlist_items.position <> excluded.position
`

// RenumberPlaylistItems makes the positions of the items of a playlist
// dense again, 0..n-1, in the order (position, id) they have (DESIGN.md
// 8.6, T5). Every change of the items ends with it, in its transaction. It
// writes only the rows that are out of place, and looks for them only when
// the positions are not dense already: they are when no two items have the
// same one and the highest is the number of the items less one. That is
// read from the index of the positions alone, while looking at every item
// costs as much as moving them all.
//
// It is an upsert of the items on themselves, because sqlc does not read
// UPDATE ... FROM: every row conflicts on its id, so nothing is inserted,
// and a row takes the place row_number() gives it. SQLite reads the whole
// SELECT into a temporary table before it writes, as for every INSERT that
// selects from its own table, so the places are those of the items as they
// were.
func (q *Queries) RenumberPlaylistItems(ctx context.Context, playlistID string) error {
	_, err := q.db.ExecContext(ctx, renumberPlaylistItems, playlistID)
	return err
}

const setPlaylistItemPosition = `-- name: SetPlaylistItemPosition :exec
UPDATE playlist_items SET position = ? WHERE id = ?
`

type SetPlaylistItemPositionParams struct {
	Position int64
	ID       string
}

// SetPlaylistItemPosition puts an item at a position.
func (q *Queries) SetPlaylistItemPosition(ctx context.Context, arg SetPlaylistItemPositionParams) error {
	_, err := q.db.ExecContext(ctx, setPlaylistItemPosition, arg.Position, arg.ID)
	return err
}

const shiftPlaylistItems = `-- name: ShiftPlaylistItems :exec
UPDATE playlist_items
SET position = position + ?1
WHERE playlist_id = ?2 AND position >= ?3 AND position <= ?4
`

type ShiftPlaylistItemsParams struct {
	Places     int64
	PlaylistID string
	First      int64
	Last       int64
}

// ShiftPlaylistItems moves the items of a playlist that are at the
// positions first..last by a number of places, to make room for a block or
// to close the place an item left. Positions are not unique (T5), so the
// rows can pass through the same value one after the other.
func (q *Queries) ShiftPlaylistItems(ctx context.Context, arg ShiftPlaylistItemsParams) error {
	_, err := q.db.ExecContext(ctx, shiftPlaylistItems,
		arg.Places,
		arg.PlaylistID,
		arg.First,
		arg.Last,
	)
	return err
}
