// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: references.sql

package store

import (
	"context"
)

const copyFavorites = `-- name: CopyFavorites :exec
INSERT INTO favorites (user_id, track_id, created_at)
SELECT old.user_id, CAST(?1 AS text), old.created_at
FROM favorites AS old
WHERE old.track_id = ?2
ON CONFLICT (user_id, track_id) DO NOTHING
`

type CopyFavoritesParams struct {
	NewID string
	OldID string
}

// CopyFavorites makes every user that has a track among its favorites have
// another track there, since the same moment. A user that already has the
// other track keeps the row it has.
func (q *Queries) CopyFavorites(ctx context.Context, arg CopyFavoritesParams) error {
	_, err := q.db.ExecContext(ctx, copyFavorites, arg.NewID, arg.OldID)
	return err
}

const deleteFavoritesOfTrack = `-- name: DeleteFavoritesOfTrack :exec
DELETE FROM favorites WHERE track_id = ?
`

// DeleteFavoritesOfTrack removes a track from the favorites of every user,
// once CopyFavorites has put the track with the same audio in its place.
func (q *Queries) DeleteFavoritesOfTrack(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, deleteFavoritesOfTrack, trackID)
	return err
}

const listAudioTwins = `-- name: ListAudioTwins :many
SELECT gone.id AS old_id, gone.first_seen_at AS old_first_seen_at,
    CAST(gone.id IN (SELECT track_id FROM playlist_items UNION SELECT track_id FROM favorites) AS INTEGER) AS referenced,
    here.id AS new_id, here.first_seen_at AS new_first_seen_at
FROM tracks AS gone
JOIN tracks AS here INDEXED BY tracks_fingerprint_idx ON here.fingerprint = gone.fingerprint AND here.available = 1
WHERE gone.available = 0
ORDER BY gone.seq, (here.album_id = gone.album_id) DESC, here.seq DESC
`

type ListAudioTwinsRow struct {
	OldID          string
	OldFirstSeenAt int64
	Referenced     int64
	NewID          string
	NewFirstSeenAt int64
}

// ListAudioTwins is how the references of the users, and the moment the
// audio was first seen, follow the audio (DESIGN.md, errata of 2026-10-02
// and of 2026-10-06, W1): a playlist item or a favorite that points to a
// track that is no longer available moves to an available track with the
// same fingerprint, and that track keeps the earlier first_seen_at of the
// two. The queries of this file are the only ones with which the scanner
// writes the tables of the users; none of them deletes a row of tracks or
// changes its id or its availability (I3, I15).
//
// It returns, for every unavailable track, the available tracks with its
// fingerprint, whatever their album and their fp_version, with whether a
// playlist item or a favorite points to the unavailable one and the
// first_seen_at of both. The first row of an old_id is the track its
// references move to: one of the same album before one of another album,
// then the row created last (the highest seq), which is the track that was
// just moved. A track without such a twin is not listed.
// The index of the twins is named: without statistics SQLite would look for
// them among every available track, through an index that begins with
// available.
func (q *Queries) ListAudioTwins(ctx context.Context) ([]ListAudioTwinsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAudioTwins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAudioTwinsRow
	for rows.Next() {
		var i ListAudioTwinsRow
		if err := rows.Scan(
			&i.OldID,
			&i.OldFirstSeenAt,
			&i.Referenced,
			&i.NewID,
			&i.NewFirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistIDsByTrack = `-- name: ListPlaylistIDsByTrack :many
SELECT DISTINCT playlist_id FROM playlist_items WHERE track_id = ? ORDER BY playlist_id
`

// ListPlaylistIDsByTrack returns the playlists that have a track among
// their items.
func (q *Queries) ListPlaylistIDsByTrack(ctx context.Context, trackID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistIDsByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var playlist_id string
		if err := rows.Scan(&playlist_id); err != nil {
			return nil, err
		}
		items = append(items, playlist_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lowerTrackFirstSeen = `-- name: LowerTrackFirstSeen :exec
UPDATE tracks SET first_seen_at = ?1
WHERE id = ?2 AND first_seen_at > ?1
`

type LowerTrackFirstSeenParams struct {
	FirstSeenAt int64
	ID          string
}

// LowerTrackFirstSeen gives a track an earlier first_seen_at: that of a
// row with the same audio which it replaces. A later one changes nothing.
func (q *Queries) LowerTrackFirstSeen(ctx context.Context, arg LowerTrackFirstSeenParams) error {
	_, err := q.db.ExecContext(ctx, lowerTrackFirstSeen, arg.FirstSeenAt, arg.ID)
	return err
}

const movePlaylistItems = `-- name: MovePlaylistItems :exec
UPDATE playlist_items SET track_id = ?1 WHERE track_id = ?2
`

type MovePlaylistItemsParams struct {
	NewID string
	OldID string
}

// MovePlaylistItems makes every playlist item of a track an item of another
// track. The id, the position and added_at of the items stay.
func (q *Queries) MovePlaylistItems(ctx context.Context, arg MovePlaylistItemsParams) error {
	_, err := q.db.ExecContext(ctx, movePlaylistItems, arg.NewID, arg.OldID)
	return err
}

const touchPlaylist = `-- name: TouchPlaylist :exec
UPDATE playlists SET revision = revision + 1, updated_at = ? WHERE id = ?
`

type TouchPlaylistParams struct {
	UpdatedAt int64
	ID        string
}

// TouchPlaylist records that the items of a playlist changed: its revision
// goes up by one (DESIGN.md 8.6).
func (q *Queries) TouchPlaylist(ctx context.Context, arg TouchPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, touchPlaylist, arg.UpdatedAt, arg.ID)
	return err
}
