// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: references.sql

package store

import (
	"context"
)

const copyFavorites = `-- name: CopyFavorites :exec
INSERT INTO favorites (user_id, track_id, created_at)
SELECT old.user_id, CAST(?1 AS text), old.created_at
FROM favorites AS old
WHERE old.track_id = ?2
ON CONFLICT (user_id, track_id) DO NOTHING
`

type CopyFavoritesParams struct {
	NewID string
	OldID string
}

// CopyFavorites makes every user that has a track among its favorites have
// another track there, since the same moment. A user that already has the
// other track keeps the row it has.
func (q *Queries) CopyFavorites(ctx context.Context, arg CopyFavoritesParams) error {
	_, err := q.db.ExecContext(ctx, copyFavorites, arg.NewID, arg.OldID)
	return err
}

const deleteFavoritesOfTrack = `-- name: DeleteFavoritesOfTrack :exec
DELETE FROM favorites WHERE track_id = ?
`

// DeleteFavoritesOfTrack removes a track from the favorites of every user,
// once CopyFavorites has put the track with the same audio in its place.
func (q *Queries) DeleteFavoritesOfTrack(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, deleteFavoritesOfTrack, trackID)
	return err
}

const listMovedReferences = `-- name: ListMovedReferences :many
SELECT gone.id AS old_id, here.id AS new_id
FROM tracks AS gone
JOIN tracks AS here ON here.fingerprint = gone.fingerprint AND here.available = 1
WHERE gone.available = 0
  AND gone.id IN (SELECT track_id FROM playlist_items UNION SELECT track_id FROM favorites)
ORDER BY gone.seq, (here.album_id = gone.album_id) DESC, here.seq DESC
`

type ListMovedReferencesRow struct {
	OldID string
	NewID string
}

// ListMovedReferences is how the references of the users follow the audio
// (DESIGN.md, erratum of 2026-10-02): a playlist item or a favorite that
// points to a track that is no longer available moves to an available track
// with the same fingerprint. The queries of this file are the only ones
// with which the scanner writes the tables of the users; none of them
// deletes or changes a row of tracks (I3).
//
// It returns, for every unavailable track that a playlist item or a
// favorite points to, the available tracks with its fingerprint, whatever
// their album and their fp_version. The first row of an old_id is the track
// its references move to: one of the same album before one of another
// album, then the row created last (the highest seq), which is the track
// that was just moved. A track without such a twin is not listed.
func (q *Queries) ListMovedReferences(ctx context.Context) ([]ListMovedReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMovedReferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMovedReferencesRow
	for rows.Next() {
		var i ListMovedReferencesRow
		if err := rows.Scan(&i.OldID, &i.NewID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylistIDsByTrack = `-- name: ListPlaylistIDsByTrack :many
SELECT DISTINCT playlist_id FROM playlist_items WHERE track_id = ? ORDER BY playlist_id
`

// ListPlaylistIDsByTrack returns the playlists that have a track among
// their items.
func (q *Queries) ListPlaylistIDsByTrack(ctx context.Context, trackID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlaylistIDsByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var playlist_id string
		if err := rows.Scan(&playlist_id); err != nil {
			return nil, err
		}
		items = append(items, playlist_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movePlaylistItems = `-- name: MovePlaylistItems :exec
UPDATE playlist_items SET track_id = ?1 WHERE track_id = ?2
`

type MovePlaylistItemsParams struct {
	NewID string
	OldID string
}

// MovePlaylistItems makes every playlist item of a track an item of another
// track. The id, the position and added_at of the items stay.
func (q *Queries) MovePlaylistItems(ctx context.Context, arg MovePlaylistItemsParams) error {
	_, err := q.db.ExecContext(ctx, movePlaylistItems, arg.NewID, arg.OldID)
	return err
}

const touchPlaylist = `-- name: TouchPlaylist :exec
UPDATE playlists SET revision = revision + 1, updated_at = ? WHERE id = ?
`

type TouchPlaylistParams struct {
	UpdatedAt int64
	ID        string
}

// TouchPlaylist records that the items of a playlist changed: its revision
// goes up by one (DESIGN.md 8.6).
func (q *Queries) TouchPlaylist(ctx context.Context, arg TouchPlaylistParams) error {
	_, err := q.db.ExecContext(ctx, touchPlaylist, arg.UpdatedAt, arg.ID)
	return err
}
