// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"
	"database/sql"
)

const getAvailableAlbumBySeq = `-- name: GetAvailableAlbumBySeq :one
SELECT albums.seq, albums.id, albums.artist_id, albums.artist_key, albums.title, albums.title_key, albums.year, albums.year_key, albums.genre, albums.compilation, albums.rel_path, albums.album_revision, albums.render_version, albums.receipt_hash, albums.cover_rel, albums.cover_sha256, albums.cover_mime, albums.cover_size, albums.cover_mtime_ns, albums.track_count, albums.duration_ms, albums.available, albums.first_seen_at, albums.updated_at, artists.name AS artist_name
FROM albums
JOIN artists ON artists.id = albums.artist_id
WHERE albums.seq = ?1 AND albums.available = 1
`

type GetAvailableAlbumBySeqRow struct {
	Album      Album
	ArtistName string
}

// GetAvailableAlbumBySeq returns the album with that seq, if it is
// available, with the name of its artist.
func (q *Queries) GetAvailableAlbumBySeq(ctx context.Context, seq int64) (GetAvailableAlbumBySeqRow, error) {
	row := q.db.QueryRowContext(ctx, getAvailableAlbumBySeq, seq)
	var i GetAvailableAlbumBySeqRow
	err := row.Scan(
		&i.Album.Seq,
		&i.Album.ID,
		&i.Album.ArtistID,
		&i.Album.ArtistKey,
		&i.Album.Title,
		&i.Album.TitleKey,
		&i.Album.Year,
		&i.Album.YearKey,
		&i.Album.Genre,
		&i.Album.Compilation,
		&i.Album.RelPath,
		&i.Album.AlbumRevision,
		&i.Album.RenderVersion,
		&i.Album.ReceiptHash,
		&i.Album.CoverRel,
		&i.Album.CoverSha256,
		&i.Album.CoverMime,
		&i.Album.CoverSize,
		&i.Album.CoverMtimeNs,
		&i.Album.TrackCount,
		&i.Album.DurationMs,
		&i.Album.Available,
		&i.Album.FirstSeenAt,
		&i.Album.UpdatedAt,
		&i.ArtistName,
	)
	return i, err
}

const getAvailableTrackBySeq = `-- name: GetAvailableTrackBySeq :one
SELECT tracks.seq, tracks.id, tracks.album_id, tracks.fingerprint, tracks.fp_version, tracks.occurrence, tracks.disc, tracks."no", tracks.title, tracks.artist, tracks.genre, tracks.rel_path, tracks.file_size, tracks.file_mtime_ns, tracks.file_sha256, tracks.codec, tracks.sample_rate, tracks.channels, tracks.bit_depth, tracks.bitrate, tracks.duration_ms, tracks.lyrics_rel, tracks.lyrics_sha256, tracks.rg_track_gain, tracks.rg_track_peak, tracks.rg_album_gain, tracks.rg_album_peak, tracks.available, tracks.updated_at, tracks.title_key, tracks.artist_key, tracks.album_key, tracks.first_seen_at,
    albums.title AS album_title, albums.year AS album_year, albums.cover_sha256 AS album_cover_sha256,
    albums.artist_id AS album_artist_id, artists.name AS album_artist_name,
    EXISTS (SELECT 1 FROM favorites
            WHERE favorites.user_id = ?1 AND favorites.track_id = tracks.id) AS favorite
FROM tracks
JOIN albums ON albums.id = tracks.album_id
JOIN artists ON artists.id = albums.artist_id
WHERE tracks.seq = ?2 AND tracks.available = 1
`

type GetAvailableTrackBySeqParams struct {
	UserID string
	Seq    int64
}

type GetAvailableTrackBySeqRow struct {
	Track            Track
	AlbumTitle       string
	AlbumYear        sql.NullInt64
	AlbumCoverSha256 sql.NullString
	AlbumArtistID    string
	AlbumArtistName  string
	Favorite         bool
}

// GetAvailableTrackBySeq returns the track with that seq, if it is
// available, with what the API shows of its album and whether it is a
// favorite of the user.
func (q *Queries) GetAvailableTrackBySeq(ctx context.Context, arg GetAvailableTrackBySeqParams) (GetAvailableTrackBySeqRow, error) {
	row := q.db.QueryRowContext(ctx, getAvailableTrackBySeq, arg.UserID, arg.Seq)
	var i GetAvailableTrackBySeqRow
	err := row.Scan(
		&i.Track.Seq,
		&i.Track.ID,
		&i.Track.AlbumID,
		&i.Track.Fingerprint,
		&i.Track.FpVersion,
		&i.Track.Occurrence,
		&i.Track.Disc,
		&i.Track.No,
		&i.Track.Title,
		&i.Track.Artist,
		&i.Track.Genre,
		&i.Track.RelPath,
		&i.Track.FileSize,
		&i.Track.FileMtimeNs,
		&i.Track.FileSha256,
		&i.Track.Codec,
		&i.Track.SampleRate,
		&i.Track.Channels,
		&i.Track.BitDepth,
		&i.Track.Bitrate,
		&i.Track.DurationMs,
		&i.Track.LyricsRel,
		&i.Track.LyricsSha256,
		&i.Track.RgTrackGain,
		&i.Track.RgTrackPeak,
		&i.Track.RgAlbumGain,
		&i.Track.RgAlbumPeak,
		&i.Track.Available,
		&i.Track.UpdatedAt,
		&i.Track.TitleKey,
		&i.Track.ArtistKey,
		&i.Track.AlbumKey,
		&i.Track.FirstSeenAt,
		&i.AlbumTitle,
		&i.AlbumYear,
		&i.AlbumCoverSha256,
		&i.AlbumArtistID,
		&i.AlbumArtistName,
		&i.Favorite,
	)
	return i, err
}

const getListedArtistBySeq = `-- name: GetListedArtistBySeq :one
SELECT artists.seq, artists.id, artists.name, artists.sort_key,
    (SELECT count(*) FROM albums
     WHERE albums.artist_id = artists.id AND albums.available = 1) AS album_count
FROM artists
WHERE artists.seq = ?1
  AND EXISTS (SELECT 1 FROM albums WHERE albums.artist_id = artists.id AND albums.available = 1)
`

type GetListedArtistBySeqRow struct {
	Artist     Artist
	AlbumCount int64
}

// GetListedArtistBySeq returns the artist with that seq, if it has at least
// one available album, with how many it has. The full-text search reads
// what it found with this query and the two below: the rowid of a row of
// the full-text tables is the seq of what it describes, and they hold only
// what the lists show (DESIGN.md 10.1, T6), so sql.ErrNoRows here means
// that the two disagree.
func (q *Queries) GetListedArtistBySeq(ctx context.Context, seq int64) (GetListedArtistBySeqRow, error) {
	row := q.db.QueryRowContext(ctx, getListedArtistBySeq, seq)
	var i GetListedArtistBySeqRow
	err := row.Scan(
		&i.Artist.Seq,
		&i.Artist.ID,
		&i.Artist.Name,
		&i.Artist.SortKey,
		&i.AlbumCount,
	)
	return i, err
}
