// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, token_hash, user_id, kind, device_name, created_at, last_used_at, expires_at)
VALUES (?1, ?2, ?3, ?4, ?5,
        ?6, ?6, ?7)
`

type CreateSessionParams struct {
	ID         string
	TokenHash  string
	UserID     string
	Kind       string
	DeviceName sql.NullString
	CreatedAt  int64
	ExpiresAt  int64
}

// CreateSession starts a session. token_hash is the SHA-256 of the token in
// hexadecimal: the token itself is never stored (I5).
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.Kind,
		arg.DeviceName,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= ?
`

// DeleteExpiredSessions removes the sessions that expired at the given time
// or before it.
func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOtherSessionsOfUser = `-- name: DeleteOtherSessionsOfUser :execrows
DELETE FROM sessions WHERE user_id = ?1 AND id <> ?2
`

type DeleteOtherSessionsOfUserParams struct {
	UserID string
	ID     string
}

// DeleteOtherSessionsOfUser revokes every session of a user but one, the
// one that asked for a change of password.
func (q *Queries) DeleteOtherSessionsOfUser(ctx context.Context, arg DeleteOtherSessionsOfUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOtherSessionsOfUser, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = ?1 AND user_id = ?2
`

type DeleteSessionParams struct {
	ID     string
	UserID string
}

// DeleteSession revokes one session of a user. A session of another user
// is not touched: the caller answers as if it did not exist (I6).
func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionsOfUser = `-- name: DeleteSessionsOfUser :execrows
DELETE FROM sessions WHERE user_id = ?
`

// DeleteSessionsOfUser revokes every session of a user.
func (q *Queries) DeleteSessionsOfUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionsOfUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.token_hash, s.user_id, s.kind, s.last_used_at, s.expires_at, u.role, u.disabled
FROM sessions AS s
JOIN users AS u ON u.id = s.user_id
WHERE s.token_hash = ?
`

type GetSessionByTokenHashRow struct {
	ID         string
	TokenHash  string
	UserID     string
	Kind       string
	LastUsedAt int64
	ExpiresAt  int64
	Role       string
	Disabled   int64
}

// GetSessionByTokenHash returns the session of a token with the role of its
// user and whether the account is disabled. No row is sql.ErrNoRows. The
// caller checks the expiry, with its own clock.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.Kind,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Role,
		&i.Disabled,
	)
	return i, err
}

const listSessionsOfUser = `-- name: ListSessionsOfUser :many
SELECT id, token_hash, user_id, kind, device_name, created_at, last_used_at, expires_at FROM sessions
WHERE user_id = ?1 AND expires_at > ?2
ORDER BY created_at DESC, id DESC
`

type ListSessionsOfUserParams struct {
	UserID string
	Now    int64
}

// ListSessionsOfUser returns the sessions of a user that have not expired
// at the given time, the newest first.
func (q *Queries) ListSessionsOfUser(ctx context.Context, arg ListSessionsOfUserParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsOfUser, arg.UserID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.UserID,
			&i.Kind,
			&i.DeviceName,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_used_at = max(last_used_at, CAST(?1 AS integer)),
    expires_at = max(expires_at, CAST(?2 AS integer))
WHERE id = ?3
`

type TouchSessionParams struct {
	LastUsedAt int64
	ExpiresAt  int64
	ID         string
}

// TouchSession records that a session was used, and renews it. Neither
// value ever goes back: of two requests that write at once, the later
// time stays.
func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastUsedAt, arg.ExpiresAt, arg.ID)
	return err
}
