// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package store

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT volume_leveling, single_key_shortcuts, theme FROM settings WHERE user_id = ?
`

type GetSettingsRow struct {
	VolumeLeveling     string
	SingleKeyShortcuts int64
	Theme              string
}

// GetSettings returns the preferences a user saved. No row is
// sql.ErrNoRows: the user never saved any, and has the defaults.
func (q *Queries) GetSettings(ctx context.Context, userID string) (GetSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSettings, userID)
	var i GetSettingsRow
	err := row.Scan(&i.VolumeLeveling, &i.SingleKeyShortcuts, &i.Theme)
	return i, err
}

const putSettings = `-- name: PutSettings :exec
INSERT INTO settings (user_id, volume_leveling, single_key_shortcuts, theme)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (user_id) DO UPDATE SET
    volume_leveling = excluded.volume_leveling,
    single_key_shortcuts = excluded.single_key_shortcuts,
    theme = excluded.theme
`

type PutSettingsParams struct {
	UserID             string
	VolumeLeveling     string
	SingleKeyShortcuts int64
	Theme              string
}

// PutSettings writes every preference of a user, creating the row at the
// first change.
func (q *Queries) PutSettings(ctx context.Context, arg PutSettingsParams) error {
	_, err := q.db.ExecContext(ctx, putSettings,
		arg.UserID,
		arg.VolumeLeveling,
		arg.SingleKeyShortcuts,
		arg.Theme,
	)
	return err
}
