// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package store

import (
	"context"
	"database/sql"
)

const listTracksByAlbum = `-- name: ListTracksByAlbum :many
SELECT seq, id, album_id, fingerprint, fp_version, occurrence, disc, "no", title, artist, genre, rel_path, file_size, file_mtime_ns, file_sha256, codec, sample_rate, channels, bit_depth, bitrate, duration_ms, lyrics_rel, lyrics_sha256, rg_track_gain, rg_track_peak, rg_album_gain, rg_album_peak, available, updated_at FROM tracks WHERE album_id = ? ORDER BY seq
`

// ListTracksByAlbum returns every row of an album, available or not, in the
// order in which the rows were created: the rows the reconciliation pairs
// with the files of a new receipt (DESIGN.md 5.4).
func (q *Queries) ListTracksByAlbum(ctx context.Context, albumID string) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.AlbumID,
			&i.Fingerprint,
			&i.FpVersion,
			&i.Occurrence,
			&i.Disc,
			&i.No,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.RelPath,
			&i.FileSize,
			&i.FileMtimeNs,
			&i.FileSha256,
			&i.Codec,
			&i.SampleRate,
			&i.Channels,
			&i.BitDepth,
			&i.Bitrate,
			&i.DurationMs,
			&i.LyricsRel,
			&i.LyricsSha256,
			&i.RgTrackGain,
			&i.RgTrackPeak,
			&i.RgAlbumGain,
			&i.RgAlbumPeak,
			&i.Available,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTrackUnavailable = `-- name: SetTrackUnavailable :exec
UPDATE tracks SET available = 0, updated_at = ? WHERE id = ?
`

type SetTrackUnavailableParams struct {
	UpdatedAt int64
	ID        string
}

// SetTrackUnavailable records that the file of a track is gone. The row
// stays, with what was last known of the track (I3): favorites and playlists
// still show it, and it comes back with the same id if its audio does.
func (q *Queries) SetTrackUnavailable(ctx context.Context, arg SetTrackUnavailableParams) error {
	_, err := q.db.ExecContext(ctx, setTrackUnavailable, arg.UpdatedAt, arg.ID)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO tracks (
    id, album_id, fingerprint, fp_version, occurrence, disc, "no", title, artist, genre,
    rel_path, file_size, file_mtime_ns, file_sha256,
    codec, sample_rate, channels, bit_depth, bitrate, duration_ms,
    lyrics_rel, lyrics_sha256,
    rg_track_gain, rg_track_peak, rg_album_gain, rg_album_peak,
    available, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?,
    1, ?
)
ON CONFLICT (id) DO UPDATE SET
    fingerprint = excluded.fingerprint,
    fp_version = excluded.fp_version,
    occurrence = excluded.occurrence,
    disc = excluded.disc,
    "no" = excluded."no",
    title = excluded.title,
    artist = excluded.artist,
    genre = excluded.genre,
    rel_path = excluded.rel_path,
    file_size = excluded.file_size,
    file_mtime_ns = excluded.file_mtime_ns,
    file_sha256 = excluded.file_sha256,
    codec = excluded.codec,
    sample_rate = excluded.sample_rate,
    channels = excluded.channels,
    bit_depth = excluded.bit_depth,
    bitrate = excluded.bitrate,
    duration_ms = excluded.duration_ms,
    lyrics_rel = excluded.lyrics_rel,
    lyrics_sha256 = excluded.lyrics_sha256,
    rg_track_gain = excluded.rg_track_gain,
    rg_track_peak = excluded.rg_track_peak,
    rg_album_gain = excluded.rg_album_gain,
    rg_album_peak = excluded.rg_album_peak,
    available = 1,
    updated_at = excluded.updated_at
WHERE tracks.album_id = excluded.album_id
`

type UpsertTrackParams struct {
	ID           string
	AlbumID      string
	Fingerprint  string
	FpVersion    string
	Occurrence   int64
	Disc         int64
	No           int64
	Title        string
	Artist       string
	Genre        sql.NullString
	RelPath      string
	FileSize     int64
	FileMtimeNs  int64
	FileSha256   string
	Codec        string
	SampleRate   int64
	Channels     int64
	BitDepth     sql.NullInt64
	Bitrate      sql.NullInt64
	DurationMs   sql.NullInt64
	LyricsRel    sql.NullString
	LyricsSha256 sql.NullString
	RgTrackGain  sql.NullFloat64
	RgTrackPeak  sql.NullFloat64
	RgAlbumGain  sql.NullFloat64
	RgAlbumPeak  sql.NullFloat64
	UpdatedAt    int64
}

// UpsertTrack creates a track, or gives a known one, found by its id, what
// its file says now, and makes it available (DESIGN.md 5.4, 6.3 step 8).
// The id and the album of a row never change (I3).
func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.ID,
		arg.AlbumID,
		arg.Fingerprint,
		arg.FpVersion,
		arg.Occurrence,
		arg.Disc,
		arg.No,
		arg.Title,
		arg.Artist,
		arg.Genre,
		arg.RelPath,
		arg.FileSize,
		arg.FileMtimeNs,
		arg.FileSha256,
		arg.Codec,
		arg.SampleRate,
		arg.Channels,
		arg.BitDepth,
		arg.Bitrate,
		arg.DurationMs,
		arg.LyricsRel,
		arg.LyricsSha256,
		arg.RgTrackGain,
		arg.RgTrackPeak,
		arg.RgAlbumGain,
		arg.RgAlbumPeak,
		arg.UpdatedAt,
	)
	return err
}
