// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package store

import (
	"context"
	"database/sql"
)

const countTracks = `-- name: CountTracks :many
SELECT available, count(*) AS total FROM tracks GROUP BY available ORDER BY available
`

type CountTracksRow struct {
	Available int64
	Total     int64
}

// CountTracks counts the tracks that are available (1) and those that are
// not (0), for the state of the library (DESIGN.md 6.5).
func (q *Queries) CountTracks(ctx context.Context) ([]CountTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, countTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTracksRow
	for rows.Next() {
		var i CountTracksRow
		if err := rows.Scan(&i.Available, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccurrences = `-- name: ListOccurrences :many
SELECT occurrence FROM tracks WHERE album_id = ? AND fingerprint = ? AND id <> ? ORDER BY occurrence
`

type ListOccurrencesParams struct {
	AlbumID     string
	Fingerprint string
	ID          string
}

// ListOccurrences returns the occurrences that the other rows of an album,
// available or not, have for a fingerprint: those a row that takes that
// fingerprint cannot have (DESIGN.md 5.4).
func (q *Queries) ListOccurrences(ctx context.Context, arg ListOccurrencesParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOccurrences, arg.AlbumID, arg.Fingerprint, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var occurrence int64
		if err := rows.Scan(&occurrence); err != nil {
			return nil, err
		}
		items = append(items, occurrence)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleFingerprints = `-- name: ListStaleFingerprints :many
SELECT tracks.seq, tracks.id, tracks.album_id, albums.rel_path AS album_rel_path, tracks.rel_path,
    tracks.file_size, tracks.file_mtime_ns, tracks.file_sha256,
    tracks.fingerprint, tracks.fp_version, tracks.occurrence
FROM tracks NOT INDEXED
JOIN albums ON albums.id = tracks.album_id
WHERE tracks.available = 1 AND tracks.fp_version <> ?1 AND tracks.seq > ?2
ORDER BY tracks.seq
LIMIT ?3
`

type ListStaleFingerprintsParams struct {
	FpVersion string
	AfterSeq  int64
	PageSize  int64
}

type ListStaleFingerprintsRow struct {
	Seq          int64
	ID           string
	AlbumID      string
	AlbumRelPath string
	RelPath      string
	FileSize     int64
	FileMtimeNs  int64
	FileSha256   string
	Fingerprint  string
	FpVersion    string
	Occurrence   int64
}

// ListStaleFingerprints returns a page of the available tracks whose
// fingerprint was computed by another ffmpeg than the current one, in the
// order of seq and after a given seq, with the folder of their album
// (DESIGN.md 6.6). Only such a fingerprint is computed again. The tracks are
// read in the order of seq, their key, and by no index: one that begins with
// available would give them in another order, to be sorted for every page.
func (q *Queries) ListStaleFingerprints(ctx context.Context, arg ListStaleFingerprintsParams) ([]ListStaleFingerprintsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleFingerprints, arg.FpVersion, arg.AfterSeq, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleFingerprintsRow
	for rows.Next() {
		var i ListStaleFingerprintsRow
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.AlbumID,
			&i.AlbumRelPath,
			&i.RelPath,
			&i.FileSize,
			&i.FileMtimeNs,
			&i.FileSha256,
			&i.Fingerprint,
			&i.FpVersion,
			&i.Occurrence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackNames = `-- name: ListTrackNames :many
SELECT id, title, artist FROM tracks ORDER BY seq
`

type ListTrackNamesRow struct {
	ID     string
	Title  string
	Artist string
}

// ListTrackNames returns the title and the artist of every track: what its
// title_key and artist_key are computed from (DESIGN.md 5.5).
func (q *Queries) ListTrackNames(ctx context.Context) ([]ListTrackNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrackNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrackNamesRow
	for rows.Next() {
		var i ListTrackNamesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Artist); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByAlbum = `-- name: ListTracksByAlbum :many
SELECT seq, id, album_id, fingerprint, fp_version, occurrence, disc, "no", title, artist, genre, rel_path, file_size, file_mtime_ns, file_sha256, codec, sample_rate, channels, bit_depth, bitrate, duration_ms, lyrics_rel, lyrics_sha256, rg_track_gain, rg_track_peak, rg_album_gain, rg_album_peak, available, updated_at, title_key, artist_key, album_key, first_seen_at FROM tracks WHERE album_id = ? ORDER BY seq
`

// ListTracksByAlbum returns every row of an album, available or not, in the
// order in which the rows were created: the rows the reconciliation pairs
// with the files of a new receipt (DESIGN.md 5.4).
func (q *Queries) ListTracksByAlbum(ctx context.Context, albumID string) ([]Track, error) {
	rows, err := q.db.QueryContext(ctx, listTracksByAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.AlbumID,
			&i.Fingerprint,
			&i.FpVersion,
			&i.Occurrence,
			&i.Disc,
			&i.No,
			&i.Title,
			&i.Artist,
			&i.Genre,
			&i.RelPath,
			&i.FileSize,
			&i.FileMtimeNs,
			&i.FileSha256,
			&i.Codec,
			&i.SampleRate,
			&i.Channels,
			&i.BitDepth,
			&i.Bitrate,
			&i.DurationMs,
			&i.LyricsRel,
			&i.LyricsSha256,
			&i.RgTrackGain,
			&i.RgTrackPeak,
			&i.RgAlbumGain,
			&i.RgAlbumPeak,
			&i.Available,
			&i.UpdatedAt,
			&i.TitleKey,
			&i.ArtistKey,
			&i.AlbumKey,
			&i.FirstSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAlbumKeyOfTracks = `-- name: SetAlbumKeyOfTracks :exec
UPDATE tracks SET album_key = ?1
WHERE album_id = ?2 AND album_key <> ?1
`

type SetAlbumKeyOfTracksParams struct {
	AlbumKey []byte
	AlbumID  string
}

// SetAlbumKeyOfTracks gives every row of an album, available or not, the
// sort key of the title of the album, of which tracks.album_key is a copy
// (the list of the tracks by album). Only the rows whose copy differs are
// written.
func (q *Queries) SetAlbumKeyOfTracks(ctx context.Context, arg SetAlbumKeyOfTracksParams) error {
	_, err := q.db.ExecContext(ctx, setAlbumKeyOfTracks, arg.AlbumKey, arg.AlbumID)
	return err
}

const setTrackFingerprint = `-- name: SetTrackFingerprint :execrows
UPDATE tracks SET
    fingerprint = ?1,
    fp_version = ?2,
    occurrence = ?3,
    updated_at = ?4
WHERE id = ?5
  AND available = 1
  AND fingerprint = ?6
  AND fp_version = ?7
  AND file_size = ?8
  AND file_mtime_ns = ?9
`

type SetTrackFingerprintParams struct {
	Fingerprint    string
	FpVersion      string
	Occurrence     int64
	UpdatedAt      int64
	ID             string
	OldFingerprint string
	OldFpVersion   string
	FileSize       int64
	FileMtimeNs    int64
}

// SetTrackFingerprint gives a row the fingerprint that the current ffmpeg
// computes for its file (DESIGN.md 6.6): the same row, with the same id
// (I3). It writes only if the row is still available and still describes
// the file that was read, with the fingerprint it had then; otherwise it
// changes nothing, and the number of rows it returns is 0.
func (q *Queries) SetTrackFingerprint(ctx context.Context, arg SetTrackFingerprintParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTrackFingerprint,
		arg.Fingerprint,
		arg.FpVersion,
		arg.Occurrence,
		arg.UpdatedAt,
		arg.ID,
		arg.OldFingerprint,
		arg.OldFpVersion,
		arg.FileSize,
		arg.FileMtimeNs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTrackSortKeys = `-- name: SetTrackSortKeys :exec
UPDATE tracks SET title_key = ?, artist_key = ? WHERE id = ?
`

type SetTrackSortKeysParams struct {
	TitleKey  []byte
	ArtistKey []byte
	ID        string
}

// SetTrackSortKeys gives a track the sort keys of its title and of its
// artist, computed again after the collation changed (DESIGN.md 5.5, T26).
func (q *Queries) SetTrackSortKeys(ctx context.Context, arg SetTrackSortKeysParams) error {
	_, err := q.db.ExecContext(ctx, setTrackSortKeys, arg.TitleKey, arg.ArtistKey, arg.ID)
	return err
}

const setTrackUnavailable = `-- name: SetTrackUnavailable :exec
UPDATE tracks SET available = 0, updated_at = ? WHERE id = ?
`

type SetTrackUnavailableParams struct {
	UpdatedAt int64
	ID        string
}

// SetTrackUnavailable records that the file of a track is gone. The row
// stays, with what was last known of the track (I3): favorites and playlists
// still show it, and it comes back with the same id if its audio does.
func (q *Queries) SetTrackUnavailable(ctx context.Context, arg SetTrackUnavailableParams) error {
	_, err := q.db.ExecContext(ctx, setTrackUnavailable, arg.UpdatedAt, arg.ID)
	return err
}

const setTracksOfAlbumUnavailable = `-- name: SetTracksOfAlbumUnavailable :exec
UPDATE tracks SET available = 0, updated_at = ? WHERE album_id = ? AND +available = 1
`

type SetTracksOfAlbumUnavailableParams struct {
	UpdatedAt int64
	AlbumID   string
}

// SetTracksOfAlbumUnavailable records that the files of every track of an
// album are gone with its folder (DESIGN.md 6.4). The rows stay (I3). The
// plus keeps SQLite from an index that begins with available, through which
// it would read every available track (see ListAvailableTracksOfAlbum; an
// UPDATE that names its index is not read by sqlc).
func (q *Queries) SetTracksOfAlbumUnavailable(ctx context.Context, arg SetTracksOfAlbumUnavailableParams) error {
	_, err := q.db.ExecContext(ctx, setTracksOfAlbumUnavailable, arg.UpdatedAt, arg.AlbumID)
	return err
}

const upsertTrack = `-- name: UpsertTrack :exec
INSERT INTO tracks (
    id, album_id, fingerprint, fp_version, occurrence, disc, "no", title, artist, genre,
    rel_path, file_size, file_mtime_ns, file_sha256,
    codec, sample_rate, channels, bit_depth, bitrate, duration_ms,
    lyrics_rel, lyrics_sha256,
    rg_track_gain, rg_track_peak, rg_album_gain, rg_album_peak,
    available, updated_at, title_key, artist_key, first_seen_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?,
    1, ?, ?, ?, ?
)
ON CONFLICT (id) DO UPDATE SET
    fingerprint = excluded.fingerprint,
    fp_version = excluded.fp_version,
    occurrence = excluded.occurrence,
    disc = excluded.disc,
    "no" = excluded."no",
    title = excluded.title,
    artist = excluded.artist,
    title_key = excluded.title_key,
    artist_key = excluded.artist_key,
    genre = excluded.genre,
    rel_path = excluded.rel_path,
    file_size = excluded.file_size,
    file_mtime_ns = excluded.file_mtime_ns,
    file_sha256 = excluded.file_sha256,
    codec = excluded.codec,
    sample_rate = excluded.sample_rate,
    channels = excluded.channels,
    bit_depth = excluded.bit_depth,
    bitrate = excluded.bitrate,
    duration_ms = excluded.duration_ms,
    lyrics_rel = excluded.lyrics_rel,
    lyrics_sha256 = excluded.lyrics_sha256,
    rg_track_gain = excluded.rg_track_gain,
    rg_track_peak = excluded.rg_track_peak,
    rg_album_gain = excluded.rg_album_gain,
    rg_album_peak = excluded.rg_album_peak,
    available = 1,
    updated_at = excluded.updated_at
WHERE tracks.album_id = excluded.album_id
`

type UpsertTrackParams struct {
	ID           string
	AlbumID      string
	Fingerprint  string
	FpVersion    string
	Occurrence   int64
	Disc         int64
	No           int64
	Title        string
	Artist       string
	Genre        sql.NullString
	RelPath      string
	FileSize     int64
	FileMtimeNs  int64
	FileSha256   string
	Codec        string
	SampleRate   int64
	Channels     int64
	BitDepth     sql.NullInt64
	Bitrate      sql.NullInt64
	DurationMs   sql.NullInt64
	LyricsRel    sql.NullString
	LyricsSha256 sql.NullString
	RgTrackGain  sql.NullFloat64
	RgTrackPeak  sql.NullFloat64
	RgAlbumGain  sql.NullFloat64
	RgAlbumPeak  sql.NullFloat64
	UpdatedAt    int64
	TitleKey     []byte
	ArtistKey    []byte
	FirstSeenAt  int64
}

// UpsertTrack creates a track, or gives a known one, found by its id, what
// its file says now, and makes it available (DESIGN.md 5.4, 6.3 step 8).
// The id and the album of a row never change (I3). title_key and
// artist_key are the sort keys of the title and of the artist (DESIGN.md
// 5.5). first_seen_at is written only when the row is created: a known row
// keeps it. album_key, the copy of the title_key of the album, is written
// for every row of the album by SetAlbumKeyOfTracks.
func (q *Queries) UpsertTrack(ctx context.Context, arg UpsertTrackParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrack,
		arg.ID,
		arg.AlbumID,
		arg.Fingerprint,
		arg.FpVersion,
		arg.Occurrence,
		arg.Disc,
		arg.No,
		arg.Title,
		arg.Artist,
		arg.Genre,
		arg.RelPath,
		arg.FileSize,
		arg.FileMtimeNs,
		arg.FileSha256,
		arg.Codec,
		arg.SampleRate,
		arg.Channels,
		arg.BitDepth,
		arg.Bitrate,
		arg.DurationMs,
		arg.LyricsRel,
		arg.LyricsSha256,
		arg.RgTrackGain,
		arg.RgTrackPeak,
		arg.RgAlbumGain,
		arg.RgAlbumPeak,
		arg.UpdatedAt,
		arg.TitleKey,
		arg.ArtistKey,
		arg.FirstSeenAt,
	)
	return err
}
