// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

// CountUsers tells whether the server has any account: the first admin is
// created only when it has none (DESIGN.md 7.4).
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, password_hash, role, disabled, created_at, password_changed_at)
VALUES (?1, ?2, ?3, ?4, 0,
        ?5, ?5)
`

type CreateUserParams struct {
	ID           string
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    int64
}

// CreateUser adds an account that is not disabled. password_hash is a PHC
// argon2id string, never a password (I5).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password_hash, role, disabled, created_at, password_changed_at FROM users WHERE id = ?
`

// GetUser returns an account by its id. No row is sql.ErrNoRows.
func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.PasswordChangedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash, role, disabled, created_at, password_changed_at FROM users WHERE username = ?
`

// GetUserByUsername returns an account by its name, which is stored in
// lower case: the caller lowers what the client sent (DESIGN.md 7.1).
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Disabled,
		&i.CreatedAt,
		&i.PasswordChangedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password_hash, role, disabled, created_at, password_changed_at FROM users ORDER BY username
`

// ListUsers returns every account, by name.
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.Disabled,
			&i.CreatedAt,
			&i.PasswordChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :execrows
UPDATE users SET password_hash = ?1, password_changed_at = ?2
WHERE id = ?3
`

type SetUserPasswordParams struct {
	PasswordHash      string
	PasswordChangedAt int64
	ID                string
}

// SetUserPassword replaces the password hash of an account. The caller
// revokes the sessions the change must end, in the same transaction.
func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setUserPassword, arg.PasswordHash, arg.PasswordChangedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
